// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function checkPermissions(content) {
  return content.includes("permissions:");
}

function checkSPDXHeader(content) {
  return content.includes("SPDX-License-Identifier:");
}

function findUnpinnedActions(content) {
  let lines = content.split("\n");
  let unpinned = [];
  Belt_Array.forEach(lines, line => {
    if (line.includes("uses:") && Belt_Option.isSome(Primitive_option.fromNull(line.match(/@[a-z0-9\\.\\-]+$/i)))) {
      line.replace("uses:", "").trim();
      return (unpinned.push(action));
    }
  });
  return unpinned;
}

function detectIssues(content) {
  let issues = [];
  if (!content.includes("permissions:")) {
    ((issues.push(issue)));
  }
  if (!content.includes("SPDX-License-Identifier:")) {
    ((issues.push(issue)));
  }
  let unpinned = findUnpinnedActions(content);
  if (unpinned.length !== 0) {
    Belt_Array.forEach(unpinned, action => ((issues.push(issue))));
  }
  if (Belt_Option.isSome(Primitive_option.fromNull(content.match(/password|token|key|secret/i))) && !content.includes("secrets.")) {
    ((issues.push(issue)));
  }
  return issues;
}

function calculateScore(result) {
  let deductions = {
    contents: 0
  };
  if (!result.hasPermissions) {
    deductions.contents = deductions.contents + 30 | 0;
  }
  if (!result.hasSPDXHeader) {
    deductions.contents = deductions.contents + 10 | 0;
  }
  deductions.contents = deductions.contents + (result.unpinnedActions.length * 15 | 0) | 0;
  Belt_Array.forEach(result.issues, issue => {
    let match = issue.level;
    switch (match) {
      case "Critical" :
        deductions.contents = deductions.contents + 20 | 0;
        return;
      case "Warning" :
        deductions.contents = deductions.contents + 10 | 0;
        return;
      case "Info" :
        deductions.contents = deductions.contents + 5 | 0;
        return;
    }
  });
  return Math.max(0, 100 - deductions.contents | 0);
}

function validateWorkflow(content) {
  let hasPermissions = content.includes("permissions:");
  let hasSPDXHeader = content.includes("SPDX-License-Identifier:");
  let unpinnedActions = findUnpinnedActions(content);
  let issues = detectIssues(content);
  let result = {
    hasPermissions: hasPermissions,
    hasSPDXHeader: hasSPDXHeader,
    unpinnedActions: unpinnedActions,
    issues: issues,
    score: 0
  };
  let score = calculateScore(result);
  return {
    hasPermissions: hasPermissions,
    hasSPDXHeader: hasSPDXHeader,
    unpinnedActions: unpinnedActions,
    issues: issues,
    score: score
  };
}

let css = `
.grim-ci-panel {
  position: fixed;
  top: 80px;
  right: 20px;
  width: 380px;
  max-height: 600px;
  overflow-y: auto;
  background: linear-gradient(135deg, #2c1a4d 0%, #1a1a2e 100%);
  border: 1px solid #5a4a7c;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
  color: #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  z-index: 10000;
}

.grim-ci-header {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 15px;
  color: #9c27b0;
}

.grim-ci-score {
  text-align: center;
  padding: 15px;
  margin-bottom: 15px;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.05);
}

.grim-ci-score-value {
  font-size: 36px;
  font-weight: 700;
  margin-bottom: 5px;
}

.grim-ci-score-label {
  font-size: 11px;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 1px;
}

.grim-ci-issue {
  padding: 10px;
  margin-bottom: 8px;
  border-left: 3px solid;
  border-radius: 4px;
  background: rgba(255, 255, 255, 0.05);
}

.grim-ci-issue.critical {
  border-color: #f44336;
}

.grim-ci-issue.warning {
  border-color: #ff9800;
}

.grim-ci-issue.info {
  border-color: #2196f3;
}

.grim-ci-issue-message {
  font-size: 13px;
  font-weight: 600;
  margin-bottom: 4px;
}

.grim-ci-issue-suggestion {
  font-size: 11px;
  color: #999;
  font-style: italic;
}

.grim-ci-close {
  position: absolute;
  top: 10px;
  right: 10px;
  background: none;
  border: none;
  color: #999;
  font-size: 24px;
  cursor: pointer;
  width: 30px;
  height: 30px;
  line-height: 1;
  padding: 0;
}

.grim-ci-close:hover {
  color: #fff;
}
`;

function levelToClass(level) {
  switch (level) {
    case "Critical" :
      return "critical";
    case "Warning" :
      return "warning";
    case "Info" :
      return "info";
  }
}

function createPanel(result) {
  GrimCore.DOM.create("div", "grim-ci-panel", undefined);
  Belt_Array.map(result.issues, issue => {
    let levelClass = levelToClass(issue.level);
    return `<div class="grim-ci-issue ` + levelClass + `">
          <div class="grim-ci-issue-message">` + issue.message + `</div>
          <div class="grim-ci-issue-suggestion">` + issue.suggestion + `</div>
        </div>`;
  }).join("");
  ((panel.innerHTML = "<div class='grim-ci-header'>CI/CD Quality Check</div>" +
    "<div class='grim-ci-score'><div class='grim-ci-score-value' style='color:" + scoreColor + "'>" + result.score + "</div><div class='grim-ci-score-label'>Workflow Score</div></div>" +
    issuesList));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.className = "grim-ci-close"));
  ((closeBtn.onclick = () => panel.remove()));
  ((panel.appendChild(closeBtn)));
  ((document.body.appendChild(panel)));
}

function run() {
  GrimCore.Log.info("GrimCIValidator running");
  GM_addStyle(css);
  let codeBlock = GrimCore.DOM.query("pre code, .blob-code-inner");
  if (codeBlock === undefined) {
    return GrimCore.Log.warn("Could not find workflow content");
  }
  let content = (el.textContent || el.innerText);
  createPanel(validateWorkflow(content));
}

if (GrimCore.URL.isGitHub() && location.href.includes("/.github/workflows/")) {
  run();
}

export {
  checkPermissions,
  checkSPDXHeader,
  findUnpinnedActions,
  detectIssues,
  calculateScore,
  validateWorkflow,
  css,
  levelToClass,
  createPanel,
  run,
}
/*  Not a pure module */
