// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function detect() {
  let host = window.location.hostname;
  if (host.includes("github.com")) {
    return "GitHub";
  } else if (host.includes("gitlab.com")) {
    return "GitLab";
  } else if (host.includes("bitbucket.org")) {
    return "Bitbucket";
  } else if (host.includes("codeberg.org")) {
    return "Codeberg";
  } else if (host.includes("sr.ht")) {
    return "SourceHut";
  } else {
    return "Unknown";
  }
}

function name(platform) {
  switch (platform) {
    case "GitHub" :
      return "GitHub";
    case "GitLab" :
      return "GitLab";
    case "Bitbucket" :
      return "Bitbucket";
    case "Codeberg" :
      return "Codeberg";
    case "SourceHut" :
      return "SourceHut";
    case "Unknown" :
      return "Unknown";
  }
}

let Platform = {
  detect: detect,
  name: name
};

function scan() {
  let path = window.location.pathname;
  let url = window.location.href;
  let platform = detect();
  let parts = Belt_Array.keep(path.split("/"), s => s !== "");
  if (parts.length < 2) {
    return;
  }
  let owner = Belt_Array.getExn(parts, 0);
  let name = Belt_Array.getExn(parts, 1);
  let branch;
  switch (platform) {
    case "GitHub" :
      let branchElem = (document.querySelector('[data-hotkey="w"] strong, .ref-selector-button-text-container'));
      branch = (branchElem == null) ? "main" : elem.textContent.trim();
      break;
    case "GitLab" :
      let branchElem$1 = (document.querySelector('.gl-dropdown-toggle-text'));
      branch = (branchElem$1 == null) ? "main" : elem.textContent.trim();
      break;
    default:
      branch = "main";
  }
  return {
    owner: owner,
    name: name,
    branch: branch,
    platform: platform,
    url: url
  };
}

function hasFile(filename, info) {
  let match = info.platform;
  switch (match) {
    case "GitHub" :
      break;
    case "GitLab" :
      break;
    case "Codeberg" :
      break;
    case "Bitbucket" :
    case "SourceHut" :
    case "Unknown" :
      break;
  }
  let elem = (document.querySelector(selector));
  return !(elem == null);
}

let Context = {
  scan: scan,
  hasFile: hasFile
};

function security(info) {
  return `# Security Policy

## Supported Versions

| Version | Supported          |
| ------- | ------------------ |
| 1.0.x   | :white_check_mark: |
| < 1.0   | :x:                |

## Reporting a Vulnerability

**Please DO NOT file a public issue.** Email security concerns to:

- **Email**: security@` + info.owner + `.dev
- **Response Time**: Within 48 hours

For more information, see our [Security Documentation](` + info.url + `/security).

## Security Measures

- All dependencies are regularly audited
- We use automated scanning (Dependabot, CodeQL)
- Security patches are prioritized

---

*This project follows the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/).*
`;
}

function codeOfConduct(info) {
  return `# Contributor Covenant Code of Conduct

## Our Pledge

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, caste, color, religion, or sexual
identity and orientation.

## Our Standards

Examples of behavior that contributes to a positive environment:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes
* Focusing on what is best not just for us as individuals, but for the overall community

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the community leaders responsible for enforcement at:

- **Email**: conduct@` + info.owner + `.dev
- **Anonymous Form**: [Report Here](` + info.url + `/issues/new?template=code_of_conduct.md)

All complaints will be reviewed and investigated promptly and fairly.

## Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage],
version 2.1, available at
[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].

[homepage]: https://www.contributor-covenant.org
[v2.1]: https://www.contributor-covenant.org/version/2/1/code_of_conduct.html
`;
}

function contributing(info) {
  return `# Contributing to ` + info.name + `

Thank you for your interest in contributing! 🎉

## Quick Links

- [Code of Conduct](CODE_OF_CONDUCT.md)
- [Security Policy](SECURITY.md)
- [Issue Tracker](` + info.url + `/issues)
- [Pull Requests](` + info.url + `/pulls)

## Getting Started

1. **Fork the repository**
2. **Clone your fork**:
   \`\`\`bash
   git clone https://github.com/` + info.owner + `/` + info.name + `.git
   cd ` + info.name + `
   \`\`\`
3. **Create a branch**:
   \`\`\`bash
   git checkout -b feature/amazing-feature
   \`\`\`
4. **Make your changes**
5. **Commit your changes**:
   \`\`\`bash
   git commit -m "Add amazing feature"
   \`\`\`
6. **Push to your fork**:
   \`\`\`bash
   git push origin feature/amazing-feature
   \`\`\`
7. **Open a Pull Request**

## Code Style

- Follow existing code conventions
- Write clear, self-documenting code
- Add comments for complex logic
- Update documentation as needed

## Testing

Before submitting a PR, ensure:
- [ ] All tests pass
- [ ] New features have tests
- [ ] Documentation is updated

## Questions?

Feel free to [open an issue](` + info.url + `/issues/new) or reach out to the maintainers.

---

*Built with ❤️ by the ` + info.name + ` community*
`;
}

function authors(info) {
  return `# Authors

This file lists the contributors to ` + info.name + `.

## Maintainers

- **` + info.owner + `** - Project Lead

## Contributors

<!-- Add contributors here -->
See [GitHub Contributors](` + info.url + `/graphs/contributors) for a full list.

## Acknowledgments

Thanks to all who have contributed to this project!

---

*Want to be listed here? See [CONTRIBUTING.md](CONTRIBUTING.md)*
`;
}

function changelog(info) {
  return `# Changelog

All notable changes to ` + info.name + ` will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial release

## [1.0.0] - ` + (new Date().toISOString().split('T')[0]) + `

### Added
- Core functionality
- Documentation
- Test suite

### Changed
- N/A

### Deprecated
- N/A

### Removed
- N/A

### Fixed
- N/A

### Security
- N/A

---

[unreleased]: ` + info.url + `/compare/v1.0.0...HEAD
[1.0.0]: ` + info.url + `/releases/tag/v1.0.0
`;
}

function citation(info) {
  return `cff-version: 1.2.0
message: "If you use ` + info.name + `, please cite it as below."
title: "` + info.name + `"
authors:
  - family-names: "` + info.owner + `"
repository-code: "` + info.url + `"
url: "` + info.url + `"
license: PMPL-1.0-or-later
date-released: ` + (new Date().toISOString().split('T')[0]) + `
version: "1.0.0"
`;
}

function support(info) {
  return `# Support

## Getting Help

- 📖 [Documentation](` + info.url + `#readme)
- 💬 [Discussions](` + info.url + `/discussions)
- 🐛 [Issue Tracker](` + info.url + `/issues)

## Before Opening an Issue

1. Search existing issues to avoid duplicates
2. Provide a clear description
3. Include reproduction steps if applicable
4. Specify your environment (OS, versions, etc.)

## Commercial Support

For commercial support, contact: support@` + info.owner + `.dev

## Community

- Follow [@` + info.owner + `](https://github.com/` + info.owner + `) for updates
- Star ⭐ the repo if you find it useful!

---

*Need help? Don't hesitate to ask!*
`;
}

function funding(info) {
  return `# Sponsor ` + info.name + `

If you find this project useful, consider sponsoring its development!

## Ways to Support

- ⭐ Star the repository
- 🐛 Report bugs and suggest features
- 💻 Contribute code
- 💰 Sponsor development

## GitHub Sponsors

Support via [GitHub Sponsors](https://github.com/sponsors/` + info.owner + `)

## Other Platforms

- [Open Collective](https://opencollective.com/` + info.owner + `)
- [Ko-fi](https://ko-fi.com/` + info.owner + `)

---

*Every contribution helps make ` + info.name + ` better!*
`;
}

let Templates = {
  security: security,
  codeOfConduct: codeOfConduct,
  contributing: contributing,
  authors: authors,
  changelog: changelog,
  citation: citation,
  support: support,
  funding: funding
};

let all = [
  {
    filename: "LICENSE",
    description: "Legal usage rights",
    priority: "Critical",
    generator: param => "PMPL-1.0-or-later\n\nSee: https://github.com/hyperpolymath/palimpsest-license",
    category: "Legal"
  },
  {
    filename: "SECURITY.md",
    description: "Vulnerability reporting",
    priority: "Critical",
    generator: security,
    category: "Security"
  },
  {
    filename: "CODE_OF_CONDUCT.md",
    description: "Community standards",
    priority: "Critical",
    generator: codeOfConduct,
    category: "Community"
  },
  {
    filename: "CONTRIBUTING.md",
    description: "Contribution guidelines",
    priority: "Important",
    generator: contributing,
    category: "Community"
  },
  {
    filename: "CHANGELOG.md",
    description: "Version history",
    priority: "Important",
    generator: changelog,
    category: "Documentation"
  },
  {
    filename: "AUTHORS.md",
    description: "Project contributors",
    priority: "Important",
    generator: authors,
    category: "Community"
  },
  {
    filename: "CITATION.cff",
    description: "Academic citation",
    priority: "Recommended",
    generator: citation,
    category: "Academic"
  },
  {
    filename: "SUPPORT.md",
    description: "Getting help",
    priority: "Recommended",
    generator: support,
    category: "Community"
  },
  {
    filename: "FUNDING.yml",
    description: "Sponsorship info",
    priority: "Recommended",
    generator: funding,
    category: "Sustainability"
  }
];

function calculateScore(missing) {
  let deductions = Belt_Array.reduce(missing, 0, (acc, std) => {
    let match = std.priority;
    let penalty;
    switch (match) {
      case "Critical" :
        penalty = 30;
        break;
      case "Important" :
        penalty = 15;
        break;
      case "Recommended" :
        penalty = 5;
        break;
    }
    return acc + penalty | 0;
  });
  return Primitive_int.max(0, 100 - deductions | 0);
}

let Standards = {
  all: all,
  calculateScore: calculateScore
};

function encodeContent(content) {
  return (encodeURIComponent(content));
}

function generateCreateURL(filename, content, info) {
  let encoded = encodeContent(content);
  let base = info.url;
  let match = info.platform;
  switch (match) {
    case "GitLab" :
      return base + `/-/new/` + info.branch + `?file_name=` + filename + `&content=` + encoded;
    case "GitHub" :
    case "Codeberg" :
      return base + `/new/` + info.branch + `?filename=` + filename + `&value=` + encoded;
    default:
      return base + `/new/` + info.branch + `?filename=` + filename;
  }
}

let URLGenerator = {
  encodeContent: encodeContent,
  generateCreateURL: generateCreateURL
};

let key = "grimtemplate_dismissed";

function isDismissed(url) {
  let stored = window.localStorage.getItem(key);
  if (stored == null) {
    return false;
  } else {
    ((JSON.parse(json)));
    return (parsed.includes(url));
  }
}

function dismiss(url) {
  let stored = window.localStorage.getItem(key);
  if (stored == null) {
    
  } else {
    ((JSON.parse(json)));
  }
  ((dismissed.push(url)));
  let updated = (JSON.stringify(dismissed));
  window.localStorage.setItem(key, updated);
}

let Storage = {
  key: key,
  isDismissed: isDismissed,
  dismiss: dismiss
};

function createPanel(missing, info) {
  if (isDismissed(info.url)) {
    console.log("✓ GrimTemplate: Panel dismissed for this repo");
    return;
  }
  calculateScore(missing);
  ((document.createElement("div")));
  ((panel.id = "grimtemplate-panel"));
  ((panel.style.cssText = "position:fixed;bottom:20px;right:20px;background:linear-gradient(135deg, #1a1a1a 0%, #2a2a2a 100%);color:#eee;padding:20px;border-radius:12px;box-shadow:0 10px 40px rgba(0,0,0,0.6);z-index:999999;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;width:380px;border:1px solid #333;backdrop-filter:blur(10px);"));
  ((document.createElement("div")));
  ((header.innerHTML = "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;'><div><strong style='font-size:16px;'>GrimTemplate</strong><div style='font-size:12px;color:#999;margin-top:2px;'>" + info.name + "</div></div><div style='text-align:right;'><div style='font-size:24px;font-weight:bold;color:" + scoreColor + ";'>" + score + "</div><div style='font-size:10px;color:#999;'>HEALTH SCORE</div></div></div>"));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.style.cssText = "position:absolute;top:10px;right:10px;background:none;border:none;color:#999;font-size:24px;cursor:pointer;padding:0;width:30px;height:30px;line-height:1;"));
  ((closeBtn.onclick = () => { panel.remove(); Storage.dismiss(info.url); }));
  ((panel.appendChild(header)));
  ((panel.appendChild(closeBtn)));
  if (missing.length === 0) {
    ((document.createElement("div")));
    ((success.innerHTML = "<div style='text-align:center;padding:20px;'><div style='font-size:48px;'>✨</div><div style='font-size:18px;color:#4caf50;margin-top:10px;'>Golden Repository!</div><div style='font-size:12px;color:#999;margin-top:5px;'>All standards met</div></div>"));
    ((panel.appendChild(success)));
    ((setTimeout(() => { panel.remove(); Storage.dismiss(info.url); }, 5000)));
  } else {
    let critical = Belt_Array.keep(missing, s => s.priority === "Critical");
    let important = Belt_Array.keep(missing, s => s.priority === "Important");
    let recommended = Belt_Array.keep(missing, s => s.priority === "Recommended");
    let renderCategory = (title, items, color) => {
      if (items.length !== 0) {
        ((document.createElement("div")));
        ((categoryDiv.innerHTML = "<div style='font-size:11px;color:" + color + ";font-weight:bold;margin:15px 0 8px;text-transform:uppercase;letter-spacing:1px;'>" + title + "</div>"));
        ((panel.appendChild(categoryDiv)));
        return Belt_Array.forEach(items, std => {
          ((document.createElement("div")));
          ((item.style.cssText = "display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;padding:10px;background:#222;border-radius:6px;border-left:3px solid " + color + ";"));
          ((document.createElement("div")));
          ((label.innerHTML = "<div style='font-size:13px;font-weight:500;'>" + std.filename + "</div><div style='font-size:11px;color:#999;margin-top:2px;'>" + std.description + "</div>"));
          let content = std.generator(info);
          generateCreateURL(std.filename, content, info);
          ((document.createElement("a")));
          ((btn.textContent = "Create"));
          ((btn.href = url));
          ((btn.target = "_blank"));
          ((btn.style.cssText = "background:" + color + ";color:white;text-decoration:none;padding:6px 14px;border-radius:6px;font-size:12px;font-weight:600;transition:transform 0.2s;"));
          ((btn.onmouseenter = () => { btn.style.transform = 'scale(1.05)'; }));
          ((btn.onmouseleave = () => { btn.style.transform = 'scale(1)'; }));
          ((item.appendChild(label)));
          ((item.appendChild(btn)));
          ((panel.appendChild(item)));
        });
      }
    };
    renderCategory("Critical", critical, "#f44336");
    renderCategory("Important", important, "#ff9800");
    renderCategory("Recommended", recommended, "#2196f3");
    ((document.createElement("div")));
    ((footer.innerHTML = "<div style='margin-top:15px;padding-top:15px;border-top:1px solid #333;font-size:11px;color:#666;text-align:center;'>Powered by <a href='https://github.com/hyperpolymath/grimrepo-scripts' style='color:#2196f3;text-decoration:none;'>GrimRepo-Scripts</a></div>"));
    ((panel.appendChild(footer)));
  }
  ((document.body.appendChild(panel)));
}

let UI = {
  createPanel: createPanel
};

function init() {
  console.log(`🎨 GrimTemplateEngine v` + METADATA_VERSION + ` - Repository Health Agent`);
  let info = scan();
  if (info !== undefined) {
    console.log(`✓ Detected: ` + info.owner + `/` + info.name + ` on ` + name(info.platform));
    let missing = Belt_Array.keep(all, std => !hasFile(std.filename, info));
    console.log(`📊 Health Score: ` + String(calculateScore(missing)) + `/100`);
    console.log(`📄 Missing ` + String(missing.length) + ` files`);
    return createPanel(missing, info);
  }
  console.log("ℹ️ No repository detected in current page");
}

init();

export {
  Platform,
  Context,
  Templates,
  Standards,
  URLGenerator,
  Storage,
  UI,
  init,
}
/*  Not a pure module */
