// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let scriptInfo_matches = ["*://*/*"];

let scriptInfo = {
  name: "grim-a11y-overlay",
  version: "1.0.0",
  description: "Accessibility testing overlay with WCAG checks",
  matches: scriptInfo_matches
};

let wcag_1_1_1 = {
  id: "1.1.1",
  level: "A",
  title: "Non-text Content"
};

let wcag_1_4_3 = {
  id: "1.4.3",
  level: "AA",
  title: "Contrast (Minimum)"
};

let wcag_1_4_6 = {
  id: "1.4.6",
  level: "AAA",
  title: "Contrast (Enhanced)"
};

let wcag_1_3_1 = {
  id: "1.3.1",
  level: "A",
  title: "Info and Relationships"
};

let wcag_2_4_1 = {
  id: "2.4.1",
  level: "A",
  title: "Bypass Blocks"
};

let wcag_2_4_7 = {
  id: "2.4.7",
  level: "AA",
  title: "Focus Visible"
};

let wcag_4_1_2 = {
  id: "4.1.2",
  level: "A",
  title: "Name, Role, Value"
};

let css = `
  .grim-a11y-overlay {
    position: fixed;
    top: 0;
    right: 0;
    width: 360px;
    height: 100vh;
    background: #ffffff;
    border-left: 1px solid #dfe6e9;
    z-index: 999999;
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    font-size: 13px;
    display: flex;
    flex-direction: column;
    box-shadow: -4px 0 12px rgba(0, 0, 0, 0.1);
  }
  .grim-a11y-header {
    padding: 16px;
    border-bottom: 1px solid #dfe6e9;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .grim-a11y-header h3 {
    margin: 0;
    font-size: 16px;
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .grim-a11y-close {
    cursor: pointer;
    font-size: 20px;
    opacity: 0.6;
    transition: opacity 0.2s;
  }
  .grim-a11y-close:hover { opacity: 1; }
  .grim-a11y-summary {
    padding: 12px 16px;
    background: #f8f9fa;
    display: flex;
    gap: 16px;
    border-bottom: 1px solid #dfe6e9;
  }
  .grim-a11y-stat {
    text-align: center;
  }
  .grim-a11y-stat-value {
    font-size: 24px;
    font-weight: 700;
  }
  .grim-a11y-stat-label {
    font-size: 11px;
    color: #636e72;
    text-transform: uppercase;
  }
  .grim-a11y-stat-error .grim-a11y-stat-value { color: #e74c3c; }
  .grim-a11y-stat-warning .grim-a11y-stat-value { color: #f39c12; }
  .grim-a11y-stat-passed .grim-a11y-stat-value { color: #27ae60; }
  .grim-a11y-issues {
    flex: 1;
    overflow-y: auto;
    padding: 0;
  }
  .grim-a11y-issue {
    padding: 12px 16px;
    border-bottom: 1px solid #f1f3f4;
    cursor: pointer;
    transition: background 0.2s;
  }
  .grim-a11y-issue:hover {
    background: #f8f9fa;
  }
  .grim-a11y-issue-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 4px;
  }
  .grim-a11y-issue-severity {
    width: 8px;
    height: 8px;
    border-radius: 50%;
  }
  .grim-a11y-issue-severity.error { background: #e74c3c; }
  .grim-a11y-issue-severity.warning { background: #f39c12; }
  .grim-a11y-issue-severity.info { background: #3498db; }
  .grim-a11y-issue-wcag {
    font-size: 10px;
    padding: 2px 6px;
    background: #e9ecef;
    border-radius: 3px;
    color: #495057;
  }
  .grim-a11y-issue-message {
    color: #2d3436;
    line-height: 1.4;
  }
  .grim-a11y-issue-suggestion {
    font-size: 11px;
    color: #636e72;
    margin-top: 4px;
    font-style: italic;
  }
  .grim-a11y-highlight {
    outline: 3px solid #e74c3c !important;
    outline-offset: 2px !important;
  }
  .grim-a11y-highlight-warning {
    outline: 3px solid #f39c12 !important;
    outline-offset: 2px !important;
  }
  .grim-a11y-actions {
    padding: 12px 16px;
    border-top: 1px solid #dfe6e9;
    display: flex;
    gap: 8px;
  }
  .grim-a11y-btn {
    flex: 1;
    padding: 8px 12px;
    border: none;
    border-radius: 4px;
    font-size: 12px;
    cursor: pointer;
    transition: background 0.2s;
  }
  .grim-a11y-btn-primary {
    background: #3498db;
    color: white;
  }
  .grim-a11y-btn-primary:hover { background: #2980b9; }
  .grim-a11y-btn-secondary {
    background: #e9ecef;
    color: #495057;
  }
  .grim-a11y-btn-secondary:hover { background: #dee2e6; }
`;

function parseColor(color) {
  let rgbMatch = (color.match(/rgb\((\d+),\s*(\d+),\s*(\d+)\)/));
  if (rgbMatch == null) {
    let rgbaMatch = (color.match(/rgba\((\d+),\s*(\d+),\s*(\d+),\s*[\d.]+\)/));
    if (rgbaMatch == null) {
      return;
    }
    let r = (parseFloat(rgbaMatch[1]));
    let g = (parseFloat(rgbaMatch[2]));
    let b = (parseFloat(rgbaMatch[3]));
    return [
      r,
      g,
      b
    ];
  }
  let r$1 = (parseFloat(rgbMatch[1]));
  let g$1 = (parseFloat(rgbMatch[2]));
  let b$1 = (parseFloat(rgbMatch[3]));
  return [
    r$1,
    g$1,
    b$1
  ];
}

function relativeLuminance(param) {
  let adjust = c => {
    let c$p = c / 255.0;
    if (c$p <= 0.03928) {
      return c$p / 12.92;
    } else {
      return Math.pow((c$p + 0.055) / 1.055, 2.4);
    }
  };
  return 0.2126 * adjust(param[0]) + 0.7152 * adjust(param[1]) + 0.0722 * adjust(param[2]);
}

function contrastRatio(l1, l2) {
  let lighter = Math.max(l1, l2);
  let darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
}

function getElementColors(el) {
  getComputedStyle(el);
  let fg = style.color;
  let bg = style.backgroundColor;
  return [
    fg,
    bg
  ];
}

function checkImageAlt() {
  let images = GrimCore.DOM.queryAll("img");
  return Belt_Array.keepMap(images, img => {
    let alt = img.getAttribute("alt");
    let src = Belt_Option.getWithDefault(Primitive_option.fromNullable(img.getAttribute("src")), "");
    if (src.includes("pixel") || src.includes("tracking")) {
      return;
    } else if (alt == null) {
      return {
        element: img,
        severity: "Error",
        message: "Image missing alt attribute",
        wcag: wcag_1_1_1,
        suggestion: "Add descriptive alt text or alt=\"\" for decorative images"
      };
    } else if (alt === "") {
      return {
        element: img,
        severity: "Info",
        message: "Image has empty alt (decorative)",
        wcag: wcag_1_1_1,
        suggestion: undefined
      };
    } else {
      return;
    }
  });
}

function checkContrast() {
  let textElements = GrimCore.DOM.queryAll("p, span, a, h1, h2, h3, h4, h5, h6, li, td, th, label, button");
  return Belt_Array.keepMap(textElements, el => {
    let match = getElementColors(el);
    if (match === undefined) {
      return;
    }
    let match$1 = parseColor(match[0]);
    let match$2 = parseColor(match[1]);
    if (match$1 === undefined) {
      return;
    }
    if (match$2 === undefined) {
      return;
    }
    let fgLum = relativeLuminance(match$1);
    let bgLum = relativeLuminance(match$2);
    let ratio = contrastRatio(fgLum, bgLum);
    if (ratio < 4.5) {
      return {
        element: el,
        severity: "Error",
        message: `Contrast ratio ` + ratio.toFixed(2) + `:1 below 4.5:1 minimum`,
        wcag: wcag_1_4_3,
        suggestion: "Increase contrast between text and background colors"
      };
    } else if (ratio < 7.0) {
      return {
        element: el,
        severity: "Warning",
        message: `Contrast ratio ` + ratio.toFixed(2) + `:1 below 7:1 (AAA)`,
        wcag: wcag_1_4_6,
        suggestion: "Consider higher contrast for AAA compliance"
      };
    } else {
      return;
    }
  });
}

function checkFormLabels() {
  let inputs = GrimCore.DOM.queryAll("input, select, textarea");
  return Belt_Array.keepMap(inputs, input => {
    let inputType = Belt_Option.getWithDefault(Primitive_option.fromNullable(input.getAttribute("type")), "text");
    if (inputType === "hidden" || inputType === "submit" || inputType === "button") {
      return;
    }
    let id = input.getAttribute("id");
    let ariaLabel = input.getAttribute("aria-label");
    let ariaLabelledBy = input.getAttribute("aria-labelledby");
    let hasLabel = (id == null) ? false : Belt_Option.isSome(GrimCore.DOM.query(`label[for="` + id + `"]`));
    if (!hasLabel && Belt_Option.isNone((ariaLabel == null) ? undefined : Primitive_option.some(ariaLabel)) && Belt_Option.isNone((ariaLabelledBy == null) ? undefined : Primitive_option.some(ariaLabelledBy))) {
      return {
        element: input,
        severity: "Error",
        message: "Form input missing associated label",
        wcag: wcag_4_1_2,
        suggestion: "Add <label for=\"id\"> or aria-label attribute"
      };
    }
  });
}

function checkHeadingHierarchy() {
  let headings = GrimCore.DOM.queryAll("h1, h2, h3, h4, h5, h6");
  let levels = Belt_Array.map(headings, h => {
    let tag = h.tagName;
    let levelStr = tag.charAt(1);
    let level = Belt_Option.getWithDefault(Belt_Int.fromString(levelStr), 0);
    return [
      h,
      level
    ];
  });
  let issues = [];
  let prevLevel = {
    contents: 0
  };
  Belt_Array.forEach(levels, param => {
    let level = param[1];
    if (level > (prevLevel.contents + 1 | 0) && prevLevel.contents > 0) {
      issues.push({
        element: param[0],
        severity: "Warning",
        message: `Skipped heading level: h` + prevLevel.contents.toString() + ` to h` + level.toString(),
        wcag: wcag_1_3_1,
        suggestion: "Maintain sequential heading levels for screen reader navigation"
      });
    }
    prevLevel.contents = level;
  });
  return issues;
}

function checkSkipLinks() {
  let skipLink = GrimCore.DOM.query("a[href='#main'], a[href='#content'], .skip-link, .skip-to-content");
  if (skipLink !== undefined) {
    return [];
  } else {
    return [{
        element: document.body,
        severity: "Warning",
        message: "No skip link found",
        wcag: wcag_2_4_1,
        suggestion: "Add a skip link at the start of the page to bypass navigation"
      }];
  }
}

function checkFocusIndicators() {
  let focusableElements = GrimCore.DOM.queryAll("a, button, input, select, textarea, [tabindex]");
  return Belt_Array.keepMap(focusableElements, el => {
    getComputedStyle(el);
    let outline = style.outlineStyle;
    let boxShadow = style.boxShadow;
    if (outline === "none" && boxShadow === "none") {
      return {
        element: el,
        severity: "Warning",
        message: "Element may have no visible focus indicator",
        wcag: wcag_2_4_7,
        suggestion: "Ensure focus is visible with outline or box-shadow"
      };
    }
  });
}

function runAudit() {
  GrimCore.Log.info("Running accessibility audit");
  let allIssues = Belt_Array.concatMany([
    checkImageAlt(),
    checkContrast(),
    checkFormLabels(),
    checkHeadingHierarchy(),
    checkSkipLinks()
  ]);
  let errors = Belt_Array.keep(allIssues, i => i.severity === "Error").length;
  let warnings = Belt_Array.keep(allIssues, i => i.severity === "Warning").length;
  return {
    issues: allIssues,
    passed: 0,
    failed: errors,
    warnings: warnings
  };
}

function severityToClass(s) {
  switch (s) {
    case "Error" :
      return "error";
    case "Warning" :
      return "warning";
    case "Info" :
      return "info";
  }
}

function renderIssue(issue, index) {
  let s = issue.suggestion;
  let suggestion = s !== undefined ? `<div class="grim-a11y-issue-suggestion">💡 ` + s + `</div>` : "";
  return `<div class="grim-a11y-issue" data-issue-index="` + index.toString() + `">
    <div class="grim-a11y-issue-header">
      <span class="grim-a11y-issue-severity ` + severityToClass(issue.severity) + `"></span>
      <span class="grim-a11y-issue-wcag">WCAG ` + issue.wcag.id + ` (` + issue.wcag.level + `)</span>
    </div>
    <div class="grim-a11y-issue-message">` + issue.message + `</div>
    ` + suggestion + `
  </div>`;
}

function showOverlay(result) {
  let el = GrimCore.DOM.query(".grim-a11y-overlay");
  if (el !== undefined) {
    Primitive_option.valFromOption(el).remove();
  }
  let overlay = GrimCore.DOM.create("div", "grim-a11y-overlay", undefined);
  let issuesHtml = Belt_Array.mapWithIndex(result.issues, (i, issue) => renderIssue(issue, i)).join("");
  overlay.innerHTML = `
    <div class="grim-a11y-header">
      <h3>♿ Accessibility Audit</h3>
      <span class="grim-a11y-close">✕</span>
    </div>
    <div class="grim-a11y-summary">
      <div class="grim-a11y-stat grim-a11y-stat-error">
        <div class="grim-a11y-stat-value">` + result.failed.toString() + `</div>
        <div class="grim-a11y-stat-label">Errors</div>
      </div>
      <div class="grim-a11y-stat grim-a11y-stat-warning">
        <div class="grim-a11y-stat-value">` + result.warnings.toString() + `</div>
        <div class="grim-a11y-stat-label">Warnings</div>
      </div>
      <div class="grim-a11y-stat grim-a11y-stat-passed">
        <div class="grim-a11y-stat-value">` + result.issues.length.toString() + `</div>
        <div class="grim-a11y-stat-label">Total</div>
      </div>
    </div>
    <div class="grim-a11y-issues">
      ` + issuesHtml + `
    </div>
    <div class="grim-a11y-actions">
      <button class="grim-a11y-btn grim-a11y-btn-primary" id="grim-a11y-rerun">
        🔄 Re-run Audit
      </button>
      <button class="grim-a11y-btn grim-a11y-btn-secondary" id="grim-a11y-export">
        📋 Export
      </button>
    </div>
  `;
  document.body.appendChild(overlay);
  let btn = GrimCore.DOM.query(".grim-a11y-close");
  if (btn !== undefined) {
    Primitive_option.valFromOption(btn).addEventListener("click", param => {
      Belt_Array.forEach(GrimCore.DOM.queryAll(".grim-a11y-highlight, .grim-a11y-highlight-warning"), el => {
        el["classList.remove"]("grim-a11y-highlight");
        el["classList.remove"]("grim-a11y-highlight-warning");
      });
      overlay.remove();
    });
  }
  Belt_Array.forEach(GrimCore.DOM.queryAll(".grim-a11y-issue"), issueEl => {
    issueEl.addEventListener("click", param => {
      let indexStr = issueEl.getAttribute("data-issue-index");
      if (indexStr == null) {
        return;
      }
      let index = Belt_Option.getWithDefault(Belt_Int.fromString(indexStr), 0);
      let issue = Belt_Array.get(result.issues, index);
      if (issue === undefined) {
        return;
      }
      Belt_Array.forEach(GrimCore.DOM.queryAll(".grim-a11y-highlight, .grim-a11y-highlight-warning"), el => {
        el["classList.remove"]("grim-a11y-highlight");
        el["classList.remove"]("grim-a11y-highlight-warning");
      });
      let highlightClass = issue.severity === "Error" ? "grim-a11y-highlight" : "grim-a11y-highlight-warning";
      issue.element["classList.add"](highlightClass);
      ((issue.element.scrollIntoView({behavior: 'smooth', block: 'center'})));
    });
  });
  let btn$1 = GrimCore.DOM.query("#grim-a11y-rerun");
  if (btn$1 !== undefined) {
    Primitive_option.valFromOption(btn$1).addEventListener("click", param => {
      overlay.remove();
      run();
    });
  }
  let btn$2 = GrimCore.DOM.query("#grim-a11y-export");
  if (btn$2 !== undefined) {
    Primitive_option.valFromOption(btn$2).addEventListener("click", param => {
      Belt_Array.map(result.issues, issue => `[` + severityToClass(issue.severity).toUpperCase() + `] WCAG ` + issue.wcag.id + `: ` + issue.message).join("\n");
      ((navigator.clipboard.writeText(report)));
      GrimCore.UI.toast("Report copied to clipboard", undefined);
    });
    return;
  }
}

function run() {
  GrimCore.Log.info("A11y Overlay running");
  GM_addStyle(css);
  showOverlay(runAudit());
}

GrimCore.Registry.register("grim-a11y-overlay", scriptInfo);

GM_registerMenuCommand("Run Accessibility Audit", run);

let wcag_2_4_6 = {
  id: "2.4.6",
  level: "AA",
  title: "Headings and Labels"
};

export {
  scriptInfo,
  wcag_1_1_1,
  wcag_1_4_3,
  wcag_1_4_6,
  wcag_1_3_1,
  wcag_2_4_1,
  wcag_2_4_6,
  wcag_2_4_7,
  wcag_4_1_2,
  css,
  parseColor,
  relativeLuminance,
  contrastRatio,
  getElementColors,
  checkImageAlt,
  checkContrast,
  checkFormLabels,
  checkHeadingHierarchy,
  checkSkipLinks,
  checkFocusIndicators,
  runAudit,
  severityToClass,
  renderIssue,
  showOverlay,
  run,
}
/*  Not a pure module */
