// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let supportedExtensions = [
  ".res",
  ".resi",
  ".js",
  ".ts",
  ".tsx",
  ".jsx",
  ".rs",
  ".ml",
  ".mli",
  ".jl",
  ".ex",
  ".exs",
  ".gleam",
  ".scm",
  ".sh",
  ".bash",
  ".yml",
  ".yaml"
];

let spdxPatterns = [
  [
    "PMPL-1\\.0(?:-or-later)?",
    "PMPL_1_0"
  ],
  [
    "MPL-2\\.0",
    "MPL_2_0"
  ],
  [
    "MIT",
    "MIT"
  ],
  [
    "Apache-2\\.0",
    "Apache_2_0"
  ],
  [
    "GPL-3\\.0",
    "GPL_3_0"
  ],
  [
    "AGPL-3\\.0",
    "AGPL_3_0"
  ],
  [
    "BSD-3-Clause",
    "BSD_3Clause"
  ]
];

function licenseToString(lic) {
  if (typeof lic === "object") {
    return `Unknown (` + lic._0 + `)`;
  }
  switch (lic) {
    case "PMPL_1_0" :
      return "MPL-2.0";
    case "MPL_2_0" :
      return "MPL-2.0";
    case "MIT" :
      return "MIT";
    case "Apache_2_0" :
      return "Apache-2.0";
    case "GPL_3_0" :
      return "GPL-3.0";
    case "AGPL_3_0" :
      return "AGPL-3.0";
    case "BSD_3Clause" :
      return "BSD-3-Clause";
  }
}

function parseSPDX(content) {
  if (!content.includes("SPDX-License-Identifier:")) {
    return "Missing";
  }
  let found = Belt_Array.reduce(spdxPatterns, undefined, (acc, param) => {
    if (acc !== undefined) {
      return acc;
    } else {
      ((new RegExp(pattern, "i")));
      if ((regex.test(content))) {
        return param[1];
      } else {
        return;
      }
    }
  });
  if (found !== undefined) {
    return {
      TAG: "Present",
      _0: found
    };
  } else {
    return {
      TAG: "Invalid",
      _0: "Unrecognized SPDX identifier"
    };
  }
}

function shouldCheckFile(path) {
  return Belt_Array.some(supportedExtensions, ext => path.endsWith(ext));
}

async function fetchFileContent(url) {
  try {
    let resp = await GrimCore.HTTP.fetch(undefined, undefined, url);
    if (resp.status === 200) {
      return resp.responseText;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function getFileListFromPage() {
  let links = GrimCore.DOM.queryAll("a[href*='/blob/']");
  return Belt_Array.slice(Belt_Array.keep(Belt_Array.map(links, link => ((link.getAttribute('href')))), href => shouldCheckFile(Belt_Option.getWithDefault(Belt_Array.get(href.split("/blob/"), 1), ""))), 0, 50);
}

async function scanRepository(repoUrl) {
  let files = getFileListFromPage();
  let filesChecked = 0;
  let filesWithHeaders = 0;
  let detectedLicenses = [];
  let allChecks = [];
  for (let i = 0, i_finish = files.length; i < i_finish; ++i) {
    let file = Belt_Array.get(files, i);
    if (file !== undefined) {
      let rawUrl = file.replace(/\/blob\//, "/raw/");
      let content = await fetchFileContent(rawUrl);
      if (content !== undefined) {
        filesChecked = filesChecked + 1 | 0;
        let status = parseSPDX(content);
        if (typeof status === "object" && status.TAG === "Present") {
          let lic = status._0;
          filesWithHeaders = filesWithHeaders + 1 | 0;
          if (!Belt_Array.some(detectedLicenses, l => Primitive_object.equal(l, lic))) {
            detectedLicenses = Belt_Array.concat(detectedLicenses, [lic]);
          }
        }
        let check = {
          path: file,
          spdxStatus: status,
          hasLicenseFile: false
        };
        allChecks = Belt_Array.concat(allChecks, [check]);
      }
    }
  }
  return {
    totalFiles: filesChecked,
    filesWithHeaders: filesWithHeaders,
    filesMissingHeaders: filesChecked - filesWithHeaders | 0,
    detectedLicenses: detectedLicenses,
    inconsistentLicenses: detectedLicenses.length > 1,
    checks: allChecks
  };
}

let css = `
.grim-license-panel {
  position: fixed;
  top: 80px;
  right: 20px;
  width: 360px;
  max-height: 600px;
  overflow-y: auto;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  border: 1px solid #3a3a5c;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
  color: #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  z-index: 10000;
}

.grim-license-header {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 15px;
  color: #4CAF50;
}

.grim-license-stat {
  display: flex;
  justify-content: space-between;
  padding: 8px 0;
  border-bottom: 1px solid #2a2a3e;
}

.grim-license-stat:last-child {
  border-bottom: none;
}

.grim-license-label {
  color: #999;
  font-size: 13px;
}

.grim-license-value {
  color: #fff;
  font-weight: 600;
  font-size: 14px;
}

.grim-license-warning {
  background: #ff9800;
  color: #000;
  padding: 10px;
  border-radius: 6px;
  margin-top: 15px;
  font-size: 12px;
  font-weight: 600;
}

.grim-license-success {
  background: #4CAF50;
  color: #000;
  padding: 10px;
  border-radius: 6px;
  margin-top: 15px;
  font-size: 12px;
  font-weight: 600;
}

.grim-license-close {
  position: absolute;
  top: 10px;
  right: 10px;
  background: none;
  border: none;
  color: #999;
  font-size: 24px;
  cursor: pointer;
  width: 30px;
  height: 30px;
  line-height: 1;
  padding: 0;
}

.grim-license-close:hover {
  color: #fff;
}

.grim-license-file-list {
  margin-top: 15px;
  max-height: 300px;
  overflow-y: auto;
}

.grim-license-file {
  padding: 6px;
  font-size: 11px;
  font-family: monospace;
  border-left: 3px solid;
  margin-bottom: 4px;
  background: rgba(255,255,255,0.05);
}

.grim-license-file.missing {
  border-color: #f44336;
}

.grim-license-file.present {
  border-color: #4CAF50;
}
`;

function createPanel(result) {
  GrimCore.DOM.create("div", "grim-license-panel", undefined);
  Belt_Array.map(result.detectedLicenses, licenseToString).join(", ");
  Belt_Array.map(Belt_Array.slice(result.checks, 0, 20), check => {
    let match = check.spdxStatus;
    let statusClass;
    statusClass = typeof match !== "object" || match.TAG !== "Present" ? "missing" : "present";
    let filename = Belt_Option.getWithDefault(Belt_Array.get(Belt_Array.reverse(check.path.split("/")), 0), check.path);
    return `<div class="grim-license-file ` + statusClass + `">` + filename + `</div>`;
  }).join("");
  ((panel.innerHTML = "<div class='grim-license-header'>License Compliance</div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Files Scanned</span><span class='grim-license-value'>" + result.totalFiles + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>With SPDX Headers</span><span class='grim-license-value'>" + result.filesWithHeaders + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Missing Headers</span><span class='grim-license-value'>" + result.filesMissingHeaders + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Compliance Rate</span><span class='grim-license-value'>" + complianceRate + "%</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Detected Licenses</span><span class='grim-license-value'>" + detectedLics + "</span></div>" +
    statusMsg +
    "<div class='grim-license-file-list'>" + fileList + "</div>"));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.className = "grim-license-close"));
  ((closeBtn.onclick = () => panel.remove()));
  ((panel.appendChild(closeBtn)));
  ((document.body.appendChild(panel)));
}

async function run() {
  GrimCore.Log.info("GrimLicenseChecker running");
  GM_addStyle(css);
  let url = location.href;
  return createPanel(await scanRepository(url));
}

if (GrimCore.URL.isGitHub() || GrimCore.URL.isGitLab()) {
  run();
}

export {
  supportedExtensions,
  spdxPatterns,
  licenseToString,
  parseSPDX,
  shouldCheckFile,
  fetchFileContent,
  getFileListFromPage,
  scanRepository,
  css,
  createPanel,
  run,
}
/*  Not a pure module */
