// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Js_promise from "@rescript/runtime/lib/es6/Js_promise.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let scriptInfo_matches = ["*://*/*"];

let scriptInfo = {
  name: "grim-dark-mode",
  version: "1.0.0",
  description: "Universal dark mode with sinople color schemes",
  matches: scriptInfo_matches
};

let schemes = [
  {
    name: "fogbinder",
    primary: "#9b59b6",
    secondary: "#1a1a2e",
    accent: "#e17055",
    background: "#0f0f23",
    text: "#f8f9fa",
    textMuted: "#a0a0a0",
    border: "#2d2d4a"
  },
  {
    name: "conative",
    primary: "#6c5ce7",
    secondary: "#16213e",
    accent: "#00b894",
    background: "#0d1117",
    text: "#e6edf3",
    textMuted: "#8b949e",
    border: "#30363d"
  },
  {
    name: "rhodium",
    primary: "#cd7f32",
    secondary: "#1a1a1a",
    accent: "#00cec9",
    background: "#0d0d0d",
    text: "#f0f0f0",
    textMuted: "#888888",
    border: "#333333"
  },
  {
    name: "zotero",
    primary: "#cc2936",
    secondary: "#1a1a1a",
    accent: "#0984e3",
    background: "#121212",
    text: "#e0e0e0",
    textMuted: "#9e9e9e",
    border: "#2d2d2d"
  },
  {
    name: "echidna",
    primary: "#2980b9",
    secondary: "#1a1a2e",
    accent: "#f39c12",
    background: "#0a0a14",
    text: "#e8e8e8",
    textMuted: "#888888",
    border: "#2a2a3e"
  },
  {
    name: "wharf",
    primary: "#27ae60",
    secondary: "#1a2634",
    accent: "#e74c3c",
    background: "#0d1821",
    text: "#ecf0f1",
    textMuted: "#7f8c8d",
    border: "#2c3e50"
  },
  {
    name: "bastion",
    primary: "#8e44ad",
    secondary: "#1a2634",
    accent: "#3498db",
    background: "#0f1624",
    text: "#ecf0f1",
    textMuted: "#7f8c8d",
    border: "#2c3e50"
  },
  {
    name: "vext",
    primary: "#1abc9c",
    secondary: "#1a1a1a",
    accent: "#e74c3c",
    background: "#0d0d0d",
    text: "#f0f0f0",
    textMuted: "#888888",
    border: "#2d2d2d"
  },
  {
    name: "palimpsest",
    primary: "#5f27cd",
    secondary: "#151520",
    accent: "#ff9f43",
    background: "#0a0a10",
    text: "#f5f6fa",
    textMuted: "#8a8a9a",
    border: "#25253a"
  },
  {
    name: "kith",
    primary: "#10ac84",
    secondary: "#151520",
    accent: "#ee5253",
    background: "#0a0a10",
    text: "#f5f6fa",
    textMuted: "#8a8a9a",
    border: "#25253a"
  }
];

let defaultScheme = "fogbinder";

function generateCSS(scheme) {
  return `
  /* Grim Dark Mode - ` + scheme.name + ` */

  :root {
    --grim-bg: ` + scheme.background + `;
    --grim-text: ` + scheme.text + `;
    --grim-text-muted: ` + scheme.textMuted + `;
    --grim-primary: ` + scheme.primary + `;
    --grim-secondary: ` + scheme.secondary + `;
    --grim-accent: ` + scheme.accent + `;
    --grim-border: ` + scheme.border + `;
  }

  html.grim-dark-mode,
  html.grim-dark-mode body {
    background-color: var(--grim-bg) !important;
    color: var(--grim-text) !important;
  }

  html.grim-dark-mode *:not(
    img, video, picture, canvas, iframe, svg,
    [class*="icon"], [class*="logo"], [class*="avatar"],
    .grim-dark-mode-panel, .grim-dark-mode-panel *
  ) {
    background-color: inherit;
    color: inherit;
    border-color: var(--grim-border) !important;
  }

  /* Headers and text */
  html.grim-dark-mode h1,
  html.grim-dark-mode h2,
  html.grim-dark-mode h3,
  html.grim-dark-mode h4,
  html.grim-dark-mode h5,
  html.grim-dark-mode h6 {
    color: var(--grim-text) !important;
  }

  html.grim-dark-mode p,
  html.grim-dark-mode span,
  html.grim-dark-mode li,
  html.grim-dark-mode td,
  html.grim-dark-mode th,
  html.grim-dark-mode label {
    color: var(--grim-text) !important;
  }

  /* Muted text */
  html.grim-dark-mode .text-muted,
  html.grim-dark-mode .text-secondary,
  html.grim-dark-mode small,
  html.grim-dark-mode .meta,
  html.grim-dark-mode time,
  html.grim-dark-mode .date {
    color: var(--grim-text-muted) !important;
  }

  /* Links */
  html.grim-dark-mode a {
    color: var(--grim-primary) !important;
  }
  html.grim-dark-mode a:hover {
    color: var(--grim-accent) !important;
  }

  /* Backgrounds */
  html.grim-dark-mode div,
  html.grim-dark-mode section,
  html.grim-dark-mode article,
  html.grim-dark-mode header,
  html.grim-dark-mode footer,
  html.grim-dark-mode nav,
  html.grim-dark-mode aside,
  html.grim-dark-mode main {
    background-color: var(--grim-bg) !important;
  }

  /* Cards and panels */
  html.grim-dark-mode .card,
  html.grim-dark-mode .panel,
  html.grim-dark-mode .box,
  html.grim-dark-mode .container,
  html.grim-dark-mode .wrapper {
    background-color: var(--grim-secondary) !important;
    border-color: var(--grim-border) !important;
  }

  /* Inputs */
  html.grim-dark-mode input,
  html.grim-dark-mode textarea,
  html.grim-dark-mode select {
    background-color: var(--grim-secondary) !important;
    color: var(--grim-text) !important;
    border-color: var(--grim-border) !important;
  }
  html.grim-dark-mode input::placeholder,
  html.grim-dark-mode textarea::placeholder {
    color: var(--grim-text-muted) !important;
  }

  /* Buttons */
  html.grim-dark-mode button,
  html.grim-dark-mode .btn,
  html.grim-dark-mode [role="button"] {
    background-color: var(--grim-primary) !important;
    color: var(--grim-bg) !important;
    border-color: var(--grim-primary) !important;
  }
  html.grim-dark-mode button:hover,
  html.grim-dark-mode .btn:hover {
    background-color: var(--grim-accent) !important;
    border-color: var(--grim-accent) !important;
  }

  /* Code */
  html.grim-dark-mode pre,
  html.grim-dark-mode code {
    background-color: ` + scheme.secondary + ` !important;
    color: ` + scheme.accent + ` !important;
  }

  /* Tables */
  html.grim-dark-mode table {
    background-color: var(--grim-bg) !important;
  }
  html.grim-dark-mode th {
    background-color: var(--grim-secondary) !important;
  }
  html.grim-dark-mode tr:nth-child(even) {
    background-color: rgba(255, 255, 255, 0.02) !important;
  }
  html.grim-dark-mode tr:hover {
    background-color: rgba(255, 255, 255, 0.05) !important;
  }

  /* Scrollbar */
  html.grim-dark-mode ::-webkit-scrollbar {
    width: 10px;
    height: 10px;
  }
  html.grim-dark-mode ::-webkit-scrollbar-track {
    background: var(--grim-bg);
  }
  html.grim-dark-mode ::-webkit-scrollbar-thumb {
    background: var(--grim-border);
    border-radius: 5px;
  }
  html.grim-dark-mode ::-webkit-scrollbar-thumb:hover {
    background: var(--grim-text-muted);
  }

  /* Selection */
  html.grim-dark-mode ::selection {
    background: var(--grim-primary);
    color: var(--grim-bg);
  }

  /* Focus */
  html.grim-dark-mode *:focus {
    outline-color: var(--grim-primary) !important;
  }
  `;
}

let panelCSS = `
  .grim-dark-mode-panel {
    position: fixed;
    bottom: 20px;
    right: 20px;
    z-index: 999999;
    background: #1a1a2e !important;
    border: 1px solid #2d2d4a !important;
    border-radius: 12px;
    padding: 16px;
    min-width: 200px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);
    font-family: -apple-system, BlinkMacSystemFont, sans-serif !important;
    color: #f8f9fa !important;
  }
  .grim-dark-mode-panel * {
    color: #f8f9fa !important;
  }
  .grim-dark-mode-toggle {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 12px;
  }
  .grim-dark-mode-toggle-label {
    font-weight: 600;
    font-size: 14px !important;
  }
  .grim-dark-mode-switch {
    position: relative;
    width: 48px;
    height: 24px;
    background: #2d2d4a;
    border-radius: 12px;
    cursor: pointer;
    transition: background 0.2s;
  }
  .grim-dark-mode-switch.active {
    background: #6c5ce7;
  }
  .grim-dark-mode-switch::after {
    content: '';
    position: absolute;
    top: 2px;
    left: 2px;
    width: 20px;
    height: 20px;
    background: #f8f9fa;
    border-radius: 50%;
    transition: transform 0.2s;
  }
  .grim-dark-mode-switch.active::after {
    transform: translateX(24px);
  }
  .grim-dark-mode-schemes {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    gap: 6px;
  }
  .grim-dark-mode-scheme {
    width: 28px;
    height: 28px;
    border-radius: 6px;
    cursor: pointer;
    border: 2px solid transparent;
    transition: border-color 0.2s, transform 0.2s;
  }
  .grim-dark-mode-scheme:hover {
    transform: scale(1.1);
  }
  .grim-dark-mode-scheme.active {
    border-color: #f8f9fa;
  }
  .grim-dark-mode-scheme-name {
    font-size: 10px !important;
    color: #a0a0a0 !important;
    text-align: center;
    margin-top: 8px;
  }
  .grim-dark-mode-collapse {
    position: absolute;
    top: 8px;
    right: 8px;
    cursor: pointer;
    opacity: 0.6;
    font-size: 16px !important;
  }
  .grim-dark-mode-collapse:hover { opacity: 1; }
  .grim-dark-mode-panel.collapsed {
    min-width: auto;
    padding: 8px 12px;
  }
  .grim-dark-mode-panel.collapsed .grim-dark-mode-schemes,
  .grim-dark-mode-panel.collapsed .grim-dark-mode-scheme-name {
    display: none;
  }
`;

let storageKey = "dark_mode";

let schemeKey = "dark_mode_scheme";

let styleElement = {
  contents: undefined
};

function getScheme(name) {
  return Belt_Array.getBy(schemes, s => s.name === name);
}

function applyScheme(scheme) {
  let el = styleElement.contents;
  if (el !== undefined) {
    Primitive_option.valFromOption(el).remove();
  }
  let style = GrimCore.DOM.create("style", undefined, "grim-dark-mode-style");
  style.innerHTML = generateCSS(scheme);
  let head = GrimCore.DOM.query("head");
  if (head !== undefined) {
    Primitive_option.valFromOption(head).appendChild(style);
  }
  styleElement.contents = Primitive_option.some(style);
  let html = GrimCore.DOM.query("html");
  if (html !== undefined) {
    Primitive_option.valFromOption(html)["classList.add"]("grim-dark-mode");
  }
  GrimCore.Log.debug(`Applied scheme: ` + scheme.name);
}

function removeScheme() {
  let el = styleElement.contents;
  if (el !== undefined) {
    Primitive_option.valFromOption(el).remove();
    styleElement.contents = undefined;
  }
  let html = GrimCore.DOM.query("html");
  if (html !== undefined) {
    Primitive_option.valFromOption(html)["classList.remove"]("grim-dark-mode");
    return;
  }
}

function isEnabled() {
  let __x = GrimCore.Storage.get("Local", storageKey);
  return Js_promise.then_(value => Promise.resolve(value === "true"), __x);
}

function getCurrentScheme() {
  let __x = GrimCore.Storage.get("Local", schemeKey);
  return Js_promise.then_(value => Promise.resolve(Belt_Option.getWithDefault(value, defaultScheme)), __x);
}

function setEnabled(enabled, schemeName) {
  if (enabled) {
    let scheme = getScheme(schemeName);
    if (scheme !== undefined) {
      applyScheme(scheme);
    }
  } else {
    removeScheme();
  }
  let __x = GrimCore.Storage.set("Local", storageKey, enabled ? "true" : "false");
  return Js_promise.then_(() => GrimCore.Storage.set("Local", schemeKey, schemeName), __x);
}

function createPanel(enabled, schemeName) {
  GM_addStyle(panelCSS);
  let panel = GrimCore.DOM.create("div", "grim-dark-mode-panel", undefined);
  let schemesHtml = Belt_Array.map(schemes, scheme => {
    let activeClass = scheme.name === schemeName ? "active" : "";
    return `<div class="grim-dark-mode-scheme ` + activeClass + `"
          data-scheme="` + scheme.name + `"
          style="background: linear-gradient(135deg, ` + scheme.primary + `, ` + scheme.accent + `)"
          title="` + scheme.name + `"></div>`;
  }).join("");
  let switchClass = enabled ? "active" : "";
  panel.innerHTML = `
    <span class="grim-dark-mode-collapse">−</span>
    <div class="grim-dark-mode-toggle">
      <span class="grim-dark-mode-toggle-label">🌙 Dark Mode</span>
      <div class="grim-dark-mode-switch ` + switchClass + `" id="grim-dark-toggle"></div>
    </div>
    <div class="grim-dark-mode-schemes">
      ` + schemesHtml + `
    </div>
    <div class="grim-dark-mode-scheme-name">` + schemeName + `</div>
  `;
  document.body.appendChild(panel);
  let toggle = GrimCore.DOM.query("#grim-dark-toggle");
  if (toggle !== undefined) {
    let toggle$1 = Primitive_option.valFromOption(toggle);
    toggle$1.addEventListener("click", param => {
      let isActive = toggle$1["classList.contains"]("active");
      let newEnabled = !isActive;
      if (newEnabled) {
        toggle$1["classList.add"]("active");
      } else {
        toggle$1["classList.remove"]("active");
      }
      let __x = getCurrentScheme();
      Js_promise.then_(scheme => setEnabled(newEnabled, scheme), __x);
    });
  }
  Belt_Array.forEach(GrimCore.DOM.queryAll(".grim-dark-mode-scheme"), schemeEl => {
    schemeEl.addEventListener("click", param => {
      let name = schemeEl.getAttribute("data-scheme");
      if (name == null) {
        return;
      }
      Belt_Array.forEach(GrimCore.DOM.queryAll(".grim-dark-mode-scheme"), el => {
        el["classList.remove"]("active");
      });
      schemeEl["classList.add"]("active");
      let nameEl = GrimCore.DOM.query(".grim-dark-mode-scheme-name");
      if (nameEl !== undefined) {
        Primitive_option.valFromOption(nameEl).textContent = name;
      }
      let __x = isEnabled();
      Js_promise.then_(enabled => {
        if (enabled) {
          setEnabled(true, name);
        } else {
          GrimCore.Storage.set("Local", schemeKey, name);
        }
        return Promise.resolve();
      }, __x);
    });
  });
  let btn = GrimCore.DOM.query(".grim-dark-mode-collapse");
  if (btn === undefined) {
    return;
  }
  let btn$1 = Primitive_option.valFromOption(btn);
  btn$1.addEventListener("click", param => {
    panel["classList.toggle"]("collapsed");
    let isCollapsed = panel["classList.contains"]("collapsed");
    btn$1.textContent = isCollapsed ? "+" : "−";
  });
}

function run() {
  GrimCore.Log.info("Dark Mode running");
  let __x = Promise.all([
    isEnabled(),
    getCurrentScheme()
  ]);
  Js_promise.then_(param => {
    let schemeName = param[1];
    let enabled = param[0];
    if (enabled) {
      let scheme = getScheme(schemeName);
      if (scheme !== undefined) {
        applyScheme(scheme);
      }
    }
    createPanel(enabled, schemeName);
    return Promise.resolve();
  }, __x);
}

GrimCore.Registry.register("grim-dark-mode", scriptInfo);

if ((document.readyState === "complete")) {
  run();
} else {
  document.body.addEventListener("DOMContentLoaded", param => run());
}

export {
  scriptInfo,
  schemes,
  defaultScheme,
  generateCSS,
  panelCSS,
  storageKey,
  schemeKey,
  styleElement,
  getScheme,
  applyScheme,
  removeScheme,
  isEnabled,
  getCurrentScheme,
  setEnabled,
  createPanel,
  run,
}
/*  Not a pure module */
