// ==UserScript==
// @name         GrimGreaser
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  Pure ReScript build system with GreasyFork auto-publish
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://github.com/*/*
// @match        *://gitlab.com/*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @grant        GM.xmlHttpRequest
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Esbuild from "esbuild";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function parseConfig(jsonStr) {
  try {
    var json = JSON.parse(jsonStr);
    var obj = Belt_Option.getExn(Js_json.decodeObject(json));
    var name = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "name"), Js_json.decodeString));
    var version = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "version"), Js_json.decodeString));
    var license = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "license"), Js_json.decodeString));
    var userScriptObj = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "userScript"), Js_json.decodeObject));
    var namespace = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "namespace"), Js_json.decodeString));
    var description = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "description"), Js_json.decodeString));
    var match = Belt_Option.getExn(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(userScriptObj, "match"), Js_json.decodeArray), (function (arr) {
                return Belt_Array.keepMap(arr, Js_json.decodeString);
              })));
    var grant = Belt_Option.getExn(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(userScriptObj, "grant"), Js_json.decodeArray), (function (arr) {
                return Belt_Array.keepMap(arr, Js_json.decodeString);
              })));
    var runAt = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "runAt"), Js_json.decodeString));
    return {
            name: name,
            version: version,
            license: license,
            userScript: {
              namespace: namespace,
              description: description,
              match: match,
              grant: grant,
              runAt: runAt
            }
          };
  }
  catch (exn){
    return ;
  }
}

function generateHeader(config) {
  var matchLines = Belt_Array.map(config.userScript.match, (function (url) {
            return "// @match       " + url;
          })).join("\n");
  var grantLines = Belt_Array.map(config.userScript.grant, (function (perm) {
            return "// @grant       " + perm;
          })).join("\n");
  return "// ==UserScript==\n// @name        " + config.name + "\n// @namespace   " + config.userScript.namespace + "\n// @version     " + config.version + "\n// @description " + config.userScript.description + "\n// @license     " + config.license + "\n" + matchLines + "\n" + grantLines + "\n// @run-at      " + config.userScript.runAt + "\n// @noframes\n// ==/UserScript==\n\n";
}

async function buildScript(entry, output, minifyOpt) {
  var minify = minifyOpt !== undefined ? minifyOpt : false;
  console.log("🔸 [ReGrease] Starting Pure ReScript Build...");
  var configPath = Deno.cwd() + "/deno.json";
  var configStr = await Deno.readTextFile(configPath);
  var c = parseConfig(configStr);
  var config = c !== undefined ? c : (console.error("❌ Failed to parse deno.json"), Deno.exit(1), Js_exn.raiseError("Config parse failed"));
  console.log("🔹 Building: " + config.name + " v" + config.version);
  var header = generateHeader(config);
  var bannerDict = {};
  bannerDict["js"] = header;
  var defineDict = {};
  defineDict["METADATA_VERSION"] = "\"" + config.version + "\"";
  defineDict["METADATA_NAME"] = "\"" + config.name + "\"";
  try {
    await Esbuild.build({
          entryPoints: [entry],
          bundle: true,
          outfile: output,
          banner: bannerDict,
          define: defineDict,
          format: "iife",
          minify: minify,
          target: "es2020"
        });
    console.log("✅ Build Complete: " + output);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    console.error("❌ Build Failed:");
    console.error(exn);
    Deno.exit(1);
  }
  Esbuild.stop();
}

async function run() {
  return await buildScript("src/Main.bs.js", "dist/userscript.user.js", false);
}

run();

export {
  parseConfig ,
  generateHeader ,
  buildScript ,
  run ,
}
/*  Not a pure module */
