// ==UserScript==
// @name         GrimPager
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  Perpetual auto-paging engine with smart detection
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @license      MPL-2.0
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let Types = {};

function rule(url, next, page, action, preload, param) {
  return {
    url: new RegExp(url, "i"),
    next: next,
    page: page,
    action: action,
    preload: preload
  };
}

let rules = [
  rule("google\\..*/search", "#pnnext", "#center_col", undefined, undefined, undefined),
  rule("bing\\.com/search", ".sb_pagN", "#b_results", undefined, undefined, undefined),
  rule("duckduckgo\\.com", ".result--more", "#links", undefined, undefined, undefined),
  rule("github\\.com/[^/]+/[^/]+/issues", ".pagination > a:last-child", ".js-navigation-container", undefined, undefined, undefined),
  rule("github\\.com/[^/]+/[^/]+/commits", ".pagination > a:last-child", ".commits-list-container", undefined, undefined, undefined),
  rule("stackoverflow\\.com/questions", ".s-pagination--item:last-child", "#questions", undefined, undefined, undefined),
  rule("gitlab\\.com", ".next_page", ".projects-list", undefined, undefined, undefined),
  rule("youtube\\.com/results", "#load-more-button", "#contents", "Dynamic", undefined, undefined),
  rule("bilibili\\.com/video", "a.next", ".bangumi-list", undefined, undefined, undefined),
  rule("twitter\\.com|x\\.com", "", "[data-testid='primaryColumn']", "Dynamic", undefined, undefined),
  rule("reddit\\.com/r/", "", "#siteTable", "Dynamic", undefined, undefined),
  rule("medium\\.com", "", "article", "Dynamic", undefined, undefined),
  rule("dev\\.to", ".crayons-pagination__link--next", ".crayons-story", undefined, undefined, undefined),
  rule("npmjs\\.com/search", ".pagination > a:last-child", ".search-results", undefined, undefined, undefined),
  rule("crates\\.io/crates", ".pagination > .next", ".crate-rows", undefined, undefined, undefined),
  rule("pypi\\.org/search", ".button--next", ".package-snippet", undefined, undefined, undefined)
];

let Database = {
  rule: rule,
  rules: rules
};

let GM = {};

let state = {
  loading: false,
  pageNum: 1,
  lastScrollY: 0.0
};

function findRule(currentUrl) {
  return Belt_Array.getBy(rules, r => r.url.test(currentUrl));
}

function detectPagination() {
  let nextPatterns = [
    "a.next",
    "a.next-page",
    ".pagination-next",
    "a[rel='next']",
    ".pager-next",
    "a:contains('Next')"
  ];
  let contentPatterns = [
    "main",
    "article",
    ".content",
    "#content",
    ".posts",
    ".items",
    ".results"
  ];
  let findFirst = patterns => Belt_Array.reduce(patterns, undefined, (acc, pattern) => {
    if (acc !== undefined) {
      return acc;
    }
    let elem = document.querySelector(pattern);
    return Belt_Option.map((elem == null) ? undefined : Primitive_option.some(elem), param => pattern);
  });
  let match = findFirst(nextPatterns);
  let match$1 = findFirst(contentPatterns);
  if (match !== undefined && match$1 !== undefined) {
    return [
      match,
      match$1
    ];
  }
}

async function loadNextPage(nextUrl, pageSelector) {
  if (state.loading) {
    console.warn("⏳ Already loading...");
    return;
  }
  state.loading = true;
  console.log(`📄 Loading: ` + nextUrl);
  try {
    await globalThis.GM.xmlHttpRequest({
      method: "GET",
      url: nextUrl
    });
    ((new DOMParser()));
    ((parser.parseFromString(response.responseText, "text/html")));
    ((doc.querySelector(pageSelector)));
    let currentContainer = document.querySelector(pageSelector);
    if (currentContainer == null) {
      console.error("❌ Container not found");
    } else {
      ((container.appendChild(newContent)));
      state.pageNum = state.pageNum + 1 | 0;
      console.log(`✅ Page ` + String(state.pageNum) + ` loaded`);
    }
    state.loading = false;
    return;
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    console.error("❌ Load failed:", exn);
    state.loading = false;
    return;
  }
}

function onScroll(nextSelector, pageSelector) {
  let currentScroll = window.scrollY;
  let threshold = body.clientHeight - window.innerHeight - 500.0;
  if (currentScroll > threshold && currentScroll > state.lastScrollY) {
    let nextLink = document.querySelector(nextSelector);
    if (nextLink == null) {
      console.warn("⚠️ No next link found");
    } else {
      let href = link.href;
      if (href !== "") {
        loadNextPage(href, pageSelector);
      }
    }
  }
  state.lastScrollY = currentScroll;
}

function init(version) {
  console.log(`🚀 GrimPager v` + version + ` - Perpetual Scrolling Engine`);
  let currentUrl = window.location.href;
  let matchedRule = findRule(currentUrl);
  if (matchedRule !== undefined) {
    console.log("✓ Rule matched - Activating auto-pager");
    ((window.addEventListener("scroll", () => onScroll(rule.next, rule.page))));
    globalThis.GM.addStyle(`
          .grimpager-indicator {
            position: fixed;
            bottom: 20px;
            right: 20px;
            padding: 10px 15px;
            background: rgba(0, 0, 0, 0.8);
            color: #fff;
            border-radius: 5px;
            font-family: monospace;
            font-size: 12px;
            z-index: 999999;
          }
        `);
  } else {
    console.log("ℹ️ No rule found - Attempting smart detection");
    let match = detectPagination();
    if (match !== undefined) {
      console.log(`🔍 Auto-detected: next=` + match[0] + `, page=` + match[1]);
      ((window.addEventListener("scroll", () => onScroll(next, page))));
    } else {
      console.log("❌ Could not detect pagination");
    }
  }
  globalThis.GM.registerMenuCommand("GrimPager: Toggle", () => {
    console.log("Menu clicked");
  });
}

let Engine = {
  GM: GM,
  state: state,
  findRule: findRule,
  detectPagination: detectPagination,
  loadNextPage: loadNextPage,
  onScroll: onScroll,
  init: init
};

init(METADATA_VERSION);

export {
  Types,
  Database,
  Engine,
}
/* rules Not a pure module */
