// ==UserScript==
// @name         GrimPager
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  Perpetual auto-paging engine with smart detection
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var Types = {};

function rule(url, next, page, action, preload, param) {
  return {
          url: new RegExp(url, "i"),
          next: next,
          page: page,
          action: action,
          preload: preload
        };
}

var rules = [
  rule("google\\..*/search", "#pnnext", "#center_col", undefined, undefined, undefined),
  rule("bing\\.com/search", ".sb_pagN", "#b_results", undefined, undefined, undefined),
  rule("duckduckgo\\.com", ".result--more", "#links", undefined, undefined, undefined),
  rule("github\\.com/[^/]+/[^/]+/issues", ".pagination > a:last-child", ".js-navigation-container", undefined, undefined, undefined),
  rule("github\\.com/[^/]+/[^/]+/commits", ".pagination > a:last-child", ".commits-list-container", undefined, undefined, undefined),
  rule("stackoverflow\\.com/questions", ".s-pagination--item:last-child", "#questions", undefined, undefined, undefined),
  rule("gitlab\\.com", ".next_page", ".projects-list", undefined, undefined, undefined),
  rule("youtube\\.com/results", "#load-more-button", "#contents", "Dynamic", undefined, undefined),
  rule("bilibili\\.com/video", "a.next", ".bangumi-list", undefined, undefined, undefined),
  rule("twitter\\.com|x\\.com", "", "[data-testid='primaryColumn']", "Dynamic", undefined, undefined),
  rule("reddit\\.com/r/", "", "#siteTable", "Dynamic", undefined, undefined),
  rule("medium\\.com", "", "article", "Dynamic", undefined, undefined),
  rule("dev\\.to", ".crayons-pagination__link--next", ".crayons-story", undefined, undefined, undefined),
  rule("npmjs\\.com/search", ".pagination > a:last-child", ".search-results", undefined, undefined, undefined),
  rule("crates\\.io/crates", ".pagination > .next", ".crate-rows", undefined, undefined, undefined),
  rule("pypi\\.org/search", ".button--next", ".package-snippet", undefined, undefined, undefined)
];

var Database = {
  rule: rule,
  rules: rules
};

var GM = {};

var state = {
  loading: false,
  pageNum: 1,
  lastScrollY: 0.0
};

function findRule(currentUrl) {
  return Belt_Array.getBy(rules, (function (r) {
                return r.url.test(currentUrl);
              }));
}

function detectPagination() {
  var nextPatterns = [
    "a.next",
    "a.next-page",
    ".pagination-next",
    "a[rel='next']",
    ".pager-next",
    "a:contains('Next')"
  ];
  var contentPatterns = [
    "main",
    "article",
    ".content",
    "#content",
    ".posts",
    ".items",
    ".results"
  ];
  var findFirst = function (patterns) {
    return Belt_Array.reduce(patterns, undefined, (function (acc, pattern) {
                  if (acc !== undefined) {
                    return acc;
                  }
                  var elem = document.querySelector(pattern);
                  return Belt_Option.map((elem == null) ? undefined : Caml_option.some(elem), (function (param) {
                                return pattern;
                              }));
                }));
  };
  var match = findFirst(nextPatterns);
  var match$1 = findFirst(contentPatterns);
  if (match !== undefined && match$1 !== undefined) {
    return [
            match,
            match$1
          ];
  }
  
}

async function loadNextPage(nextUrl, pageSelector) {
  if (state.loading) {
    console.warn("⏳ Already loading...");
    return ;
  }
  state.loading = true;
  console.log("📄 Loading: " + nextUrl);
  try {
    await GM.xmlHttpRequest({
          method: "GET",
          url: nextUrl
        });
    ((new DOMParser()));
    ((parser.parseFromString(response.responseText, "text/html")));
    ((doc.querySelector(pageSelector)));
    var currentContainer = document.querySelector(pageSelector);
    if (currentContainer == null) {
      console.error("❌ Container not found");
    } else {
      ((container.appendChild(newContent)));
      state.pageNum = state.pageNum + 1 | 0;
      console.log("✅ Page " + String(state.pageNum) + " loaded");
    }
    state.loading = false;
    return ;
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    console.error("❌ Load failed:", exn);
    state.loading = false;
    return ;
  }
}

function onScroll(nextSelector, pageSelector) {
  var currentScroll = window.scrollY;
  var threshold = body.clientHeight - window.innerHeight - 500.0;
  if (currentScroll > threshold && currentScroll > state.lastScrollY) {
    var nextLink = document.querySelector(nextSelector);
    if (nextLink == null) {
      console.warn("⚠️ No next link found");
    } else {
      var href = link.href;
      if (href !== "") {
        loadNextPage(href, pageSelector);
      }
      
    }
  }
  state.lastScrollY = currentScroll;
}

function init(version) {
  console.log("🚀 GrimPager v" + version + " - Perpetual Scrolling Engine");
  var currentUrl = window.location.href;
  var matchedRule = findRule(currentUrl);
  if (matchedRule !== undefined) {
    console.log("✓ Rule matched - Activating auto-pager");
    ((window.addEventListener("scroll", () => onScroll(rule.next, rule.page))));
    GM.addStyle("\n          .grimpager-indicator {\n            position: fixed;\n            bottom: 20px;\n            right: 20px;\n            padding: 10px 15px;\n            background: rgba(0, 0, 0, 0.8);\n            color: #fff;\n            border-radius: 5px;\n            font-family: monospace;\n            font-size: 12px;\n            z-index: 999999;\n          }\n        ");
  } else {
    console.log("ℹ️ No rule found - Attempting smart detection");
    var match = detectPagination();
    if (match !== undefined) {
      console.log("🔍 Auto-detected: next=" + match[0] + ", page=" + match[1]);
      ((window.addEventListener("scroll", () => onScroll(next, page))));
    } else {
      console.log("❌ Could not detect pagination");
    }
  }
  GM.registerMenuCommand("GrimPager: Toggle", (function () {
          console.log("Menu clicked");
        }));
}

var Engine = {
  GM: GM,
  state: state,
  findRule: findRule,
  detectPagination: detectPagination,
  loadNextPage: loadNextPage,
  onScroll: onScroll,
  init: init
};

init(METADATA_VERSION);

export {
  Types ,
  Database ,
  Engine ,
}
/* rules Not a pure module */
