// ==UserScript==
// @name         GrimTemplateEngine
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  Intelligent repository health agent with context-aware templates
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://github.com/*/*
// @match        *://gitlab.com/*/*
// @match        *://bitbucket.org/*/*
// @match        *://codeberg.org/*/*
// @match        *://sr.ht/*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function detect() {
  var host = window.location.hostname;
  if (host.includes("github.com")) {
    return "GitHub";
  } else if (host.includes("gitlab.com")) {
    return "GitLab";
  } else if (host.includes("bitbucket.org")) {
    return "Bitbucket";
  } else if (host.includes("codeberg.org")) {
    return "Codeberg";
  } else if (host.includes("sr.ht")) {
    return "SourceHut";
  } else {
    return "Unknown";
  }
}

function name(platform) {
  switch (platform) {
    case "GitHub" :
        return "GitHub";
    case "GitLab" :
        return "GitLab";
    case "Bitbucket" :
        return "Bitbucket";
    case "Codeberg" :
        return "Codeberg";
    case "SourceHut" :
        return "SourceHut";
    case "Unknown" :
        return "Unknown";
    
  }
}

var Platform = {
  detect: detect,
  name: name
};

function scan() {
  var path = window.location.pathname;
  var url = window.location.href;
  var platform = detect();
  var parts = Belt_Array.keep(path.split("/"), (function (s) {
          return s !== "";
        }));
  if (parts.length < 2) {
    return ;
  }
  var owner = Belt_Array.getExn(parts, 0);
  var name = Belt_Array.getExn(parts, 1);
  var branch;
  switch (platform) {
    case "GitHub" :
        var branchElem = (document.querySelector('[data-hotkey="w"] strong, .ref-selector-button-text-container'));
        branch = (branchElem == null) ? "main" : elem.textContent.trim();
        break;
    case "GitLab" :
        var branchElem$1 = (document.querySelector('.gl-dropdown-toggle-text'));
        branch = (branchElem$1 == null) ? "main" : elem.textContent.trim();
        break;
    default:
      branch = "main";
  }
  return {
          owner: owner,
          name: name,
          branch: branch,
          platform: platform,
          url: url
        };
}

function hasFile(filename, info) {
  var match = info.platform;
  switch (match) {
    case "GitHub" :
        break;
    case "GitLab" :
        break;
    case "Codeberg" :
        break;
    case "Bitbucket" :
    case "SourceHut" :
    case "Unknown" :
        break;
    
  }
  var elem = (document.querySelector(selector));
  return !(elem == null);
}

var Context = {
  scan: scan,
  hasFile: hasFile
};

function security(info) {
  return "# Security Policy\n\n## Supported Versions\n\n| Version | Supported          |\n| ------- | ------------------ |\n| 1.0.x   | :white_check_mark: |\n| < 1.0   | :x:                |\n\n## Reporting a Vulnerability\n\n**Please DO NOT file a public issue.** Email security concerns to:\n\n- **Email**: security@" + info.owner + ".dev\n- **Response Time**: Within 48 hours\n\nFor more information, see our [Security Documentation](" + info.url + "/security).\n\n## Security Measures\n\n- All dependencies are regularly audited\n- We use automated scanning (Dependabot, CodeQL)\n- Security patches are prioritized\n\n---\n\n*This project follows the [OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/).*\n";
}

function codeOfConduct(info) {
  return "# Contributor Covenant Code of Conduct\n\n## Our Pledge\n\nWe as members, contributors, and leaders pledge to make participation in our\ncommunity a harassment-free experience for everyone, regardless of age, body\nsize, visible or invisible disability, ethnicity, sex characteristics, gender\nidentity and expression, level of experience, education, socio-economic status,\nnationality, personal appearance, race, caste, color, religion, or sexual\nidentity and orientation.\n\n## Our Standards\n\nExamples of behavior that contributes to a positive environment:\n\n* Demonstrating empathy and kindness toward other people\n* Being respectful of differing opinions, viewpoints, and experiences\n* Giving and gracefully accepting constructive feedback\n* Accepting responsibility and apologizing to those affected by our mistakes\n* Focusing on what is best not just for us as individuals, but for the overall community\n\n## Enforcement\n\nInstances of abusive, harassing, or otherwise unacceptable behavior may be\nreported to the community leaders responsible for enforcement at:\n\n- **Email**: conduct@" + info.owner + ".dev\n- **Anonymous Form**: [Report Here](" + info.url + "/issues/new?template=code_of_conduct.md)\n\nAll complaints will be reviewed and investigated promptly and fairly.\n\n## Attribution\n\nThis Code of Conduct is adapted from the [Contributor Covenant][homepage],\nversion 2.1, available at\n[https://www.contributor-covenant.org/version/2/1/code_of_conduct.html][v2.1].\n\n[homepage]: https://www.contributor-covenant.org\n[v2.1]: https://www.contributor-covenant.org/version/2/1/code_of_conduct.html\n";
}

function contributing(info) {
  return "# Contributing to " + info.name + "\n\nThank you for your interest in contributing! 🎉\n\n## Quick Links\n\n- [Code of Conduct](CODE_OF_CONDUCT.md)\n- [Security Policy](SECURITY.md)\n- [Issue Tracker](" + info.url + "/issues)\n- [Pull Requests](" + info.url + "/pulls)\n\n## Getting Started\n\n1. **Fork the repository**\n2. **Clone your fork**:\n   \`\`\`bash\n   git clone https://github.com/" + info.owner + "/" + info.name + ".git\n   cd " + info.name + "\n   \`\`\`\n3. **Create a branch**:\n   \`\`\`bash\n   git checkout -b feature/amazing-feature\n   \`\`\`\n4. **Make your changes**\n5. **Commit your changes**:\n   \`\`\`bash\n   git commit -m \"Add amazing feature\"\n   \`\`\`\n6. **Push to your fork**:\n   \`\`\`bash\n   git push origin feature/amazing-feature\n   \`\`\`\n7. **Open a Pull Request**\n\n## Code Style\n\n- Follow existing code conventions\n- Write clear, self-documenting code\n- Add comments for complex logic\n- Update documentation as needed\n\n## Testing\n\nBefore submitting a PR, ensure:\n- [ ] All tests pass\n- [ ] New features have tests\n- [ ] Documentation is updated\n\n## Questions?\n\nFeel free to [open an issue](" + info.url + "/issues/new) or reach out to the maintainers.\n\n---\n\n*Built with ❤️ by the " + info.name + " community*\n";
}

function authors(info) {
  return "# Authors\n\nThis file lists the contributors to " + info.name + ".\n\n## Maintainers\n\n- **" + info.owner + "** - Project Lead\n\n## Contributors\n\n<!-- Add contributors here -->\nSee [GitHub Contributors](" + info.url + "/graphs/contributors) for a full list.\n\n## Acknowledgments\n\nThanks to all who have contributed to this project!\n\n---\n\n*Want to be listed here? See [CONTRIBUTING.md](CONTRIBUTING.md)*\n";
}

function changelog(info) {
  return "# Changelog\n\nAll notable changes to " + info.name + " will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n## [Unreleased]\n\n### Added\n- Initial release\n\n## [1.0.0] - " + (new Date().toISOString().split('T')[0]) + "\n\n### Added\n- Core functionality\n- Documentation\n- Test suite\n\n### Changed\n- N/A\n\n### Deprecated\n- N/A\n\n### Removed\n- N/A\n\n### Fixed\n- N/A\n\n### Security\n- N/A\n\n---\n\n[unreleased]: " + info.url + "/compare/v1.0.0...HEAD\n[1.0.0]: " + info.url + "/releases/tag/v1.0.0\n";
}

function citation(info) {
  return "cff-version: 1.2.0\nmessage: \"If you use " + info.name + ", please cite it as below.\"\ntitle: \"" + info.name + "\"\nauthors:\n  - family-names: \"" + info.owner + "\"\nrepository-code: \"" + info.url + "\"\nurl: \"" + info.url + "\"\nlicense: PMPL-1.0-or-later\ndate-released: " + (new Date().toISOString().split('T')[0]) + "\nversion: \"1.0.0\"\n";
}

function support(info) {
  return "# Support\n\n## Getting Help\n\n- 📖 [Documentation](" + info.url + "#readme)\n- 💬 [Discussions](" + info.url + "/discussions)\n- 🐛 [Issue Tracker](" + info.url + "/issues)\n\n## Before Opening an Issue\n\n1. Search existing issues to avoid duplicates\n2. Provide a clear description\n3. Include reproduction steps if applicable\n4. Specify your environment (OS, versions, etc.)\n\n## Commercial Support\n\nFor commercial support, contact: support@" + info.owner + ".dev\n\n## Community\n\n- Follow [@" + info.owner + "](https://github.com/" + info.owner + ") for updates\n- Star ⭐ the repo if you find it useful!\n\n---\n\n*Need help? Don't hesitate to ask!*\n";
}

function funding(info) {
  return "# Sponsor " + info.name + "\n\nIf you find this project useful, consider sponsoring its development!\n\n## Ways to Support\n\n- ⭐ Star the repository\n- 🐛 Report bugs and suggest features\n- 💻 Contribute code\n- 💰 Sponsor development\n\n## GitHub Sponsors\n\nSupport via [GitHub Sponsors](https://github.com/sponsors/" + info.owner + ")\n\n## Other Platforms\n\n- [Open Collective](https://opencollective.com/" + info.owner + ")\n- [Ko-fi](https://ko-fi.com/" + info.owner + ")\n\n---\n\n*Every contribution helps make " + info.name + " better!*\n";
}

var Templates = {
  security: security,
  codeOfConduct: codeOfConduct,
  contributing: contributing,
  authors: authors,
  changelog: changelog,
  citation: citation,
  support: support,
  funding: funding
};

var all = [
  {
    filename: "LICENSE",
    description: "Legal usage rights",
    priority: "Critical",
    generator: (function (param) {
        return "PMPL-1.0-or-later\n\nSee: https://github.com/hyperpolymath/palimpsest-license";
      }),
    category: "Legal"
  },
  {
    filename: "SECURITY.md",
    description: "Vulnerability reporting",
    priority: "Critical",
    generator: security,
    category: "Security"
  },
  {
    filename: "CODE_OF_CONDUCT.md",
    description: "Community standards",
    priority: "Critical",
    generator: codeOfConduct,
    category: "Community"
  },
  {
    filename: "CONTRIBUTING.md",
    description: "Contribution guidelines",
    priority: "Important",
    generator: contributing,
    category: "Community"
  },
  {
    filename: "CHANGELOG.md",
    description: "Version history",
    priority: "Important",
    generator: changelog,
    category: "Documentation"
  },
  {
    filename: "AUTHORS.md",
    description: "Project contributors",
    priority: "Important",
    generator: authors,
    category: "Community"
  },
  {
    filename: "CITATION.cff",
    description: "Academic citation",
    priority: "Recommended",
    generator: citation,
    category: "Academic"
  },
  {
    filename: "SUPPORT.md",
    description: "Getting help",
    priority: "Recommended",
    generator: support,
    category: "Community"
  },
  {
    filename: "FUNDING.yml",
    description: "Sponsorship info",
    priority: "Recommended",
    generator: funding,
    category: "Sustainability"
  }
];

function calculateScore(missing) {
  var deductions = Belt_Array.reduce(missing, 0, (function (acc, std) {
          var match = std.priority;
          var penalty;
          switch (match) {
            case "Critical" :
                penalty = 30;
                break;
            case "Important" :
                penalty = 15;
                break;
            case "Recommended" :
                penalty = 5;
                break;
            
          }
          return acc + penalty | 0;
        }));
  return Caml.int_max(0, 100 - deductions | 0);
}

var Standards = {
  all: all,
  calculateScore: calculateScore
};

function encodeContent(content) {
  return (encodeURIComponent(content));
}

function generateCreateURL(filename, content, info) {
  var encoded = encodeContent(content);
  var base = info.url;
  var match = info.platform;
  switch (match) {
    case "GitLab" :
        return base + "/-/new/" + info.branch + "?file_name=" + filename + "&content=" + encoded;
    case "GitHub" :
    case "Codeberg" :
        return base + "/new/" + info.branch + "?filename=" + filename + "&value=" + encoded;
    default:
      return base + "/new/" + info.branch + "?filename=" + filename;
  }
}

var URLGenerator = {
  encodeContent: encodeContent,
  generateCreateURL: generateCreateURL
};

var key = "grimtemplate_dismissed";

function isDismissed(url) {
  var stored = window.localStorage.getItem(key);
  if (stored == null) {
    return false;
  } else {
    ((JSON.parse(json)));
    return (parsed.includes(url));
  }
}

function dismiss(url) {
  var stored = window.localStorage.getItem(key);
  if (stored == null) {
    
  } else {
    ((JSON.parse(json)));
  }
  ((dismissed.push(url)));
  var updated = (JSON.stringify(dismissed));
  window.localStorage.setItem(key, updated);
}

var $$Storage = {
  key: key,
  isDismissed: isDismissed,
  dismiss: dismiss
};

function createPanel(missing, info) {
  if (isDismissed(info.url)) {
    console.log("✓ GrimTemplate: Panel dismissed for this repo");
    return ;
  }
  calculateScore(missing);
  ((document.createElement("div")));
  ((panel.id = "grimtemplate-panel"));
  ((panel.style.cssText = "position:fixed;bottom:20px;right:20px;background:linear-gradient(135deg, #1a1a1a 0%, #2a2a2a 100%);color:#eee;padding:20px;border-radius:12px;box-shadow:0 10px 40px rgba(0,0,0,0.6);z-index:999999;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;width:380px;border:1px solid #333;backdrop-filter:blur(10px);"));
  ((document.createElement("div")));
  ((header.innerHTML = "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;'><div><strong style='font-size:16px;'>GrimTemplate</strong><div style='font-size:12px;color:#999;margin-top:2px;'>" + info.name + "</div></div><div style='text-align:right;'><div style='font-size:24px;font-weight:bold;color:" + scoreColor + ";'>" + score + "</div><div style='font-size:10px;color:#999;'>HEALTH SCORE</div></div></div>"));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.style.cssText = "position:absolute;top:10px;right:10px;background:none;border:none;color:#999;font-size:24px;cursor:pointer;padding:0;width:30px;height:30px;line-height:1;"));
  ((closeBtn.onclick = () => { panel.remove(); Storage.dismiss(info.url); }));
  ((panel.appendChild(header)));
  ((panel.appendChild(closeBtn)));
  if (missing.length === 0) {
    ((document.createElement("div")));
    ((success.innerHTML = "<div style='text-align:center;padding:20px;'><div style='font-size:48px;'>✨</div><div style='font-size:18px;color:#4caf50;margin-top:10px;'>Golden Repository!</div><div style='font-size:12px;color:#999;margin-top:5px;'>All standards met</div></div>"));
    ((panel.appendChild(success)));
    ((setTimeout(() => { panel.remove(); Storage.dismiss(info.url); }, 5000)));
  } else {
    var critical = Belt_Array.keep(missing, (function (s) {
            return s.priority === "Critical";
          }));
    var important = Belt_Array.keep(missing, (function (s) {
            return s.priority === "Important";
          }));
    var recommended = Belt_Array.keep(missing, (function (s) {
            return s.priority === "Recommended";
          }));
    var renderCategory = function (title, items, color) {
      if (items.length !== 0) {
        ((document.createElement("div")));
        ((categoryDiv.innerHTML = "<div style='font-size:11px;color:" + color + ";font-weight:bold;margin:15px 0 8px;text-transform:uppercase;letter-spacing:1px;'>" + title + "</div>"));
        ((panel.appendChild(categoryDiv)));
        return Belt_Array.forEach(items, (function (std) {
                      ((document.createElement("div")));
                      ((item.style.cssText = "display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;padding:10px;background:#222;border-radius:6px;border-left:3px solid " + color + ";"));
                      ((document.createElement("div")));
                      ((label.innerHTML = "<div style='font-size:13px;font-weight:500;'>" + std.filename + "</div><div style='font-size:11px;color:#999;margin-top:2px;'>" + std.description + "</div>"));
                      var content = std.generator(info);
                      generateCreateURL(std.filename, content, info);
                      ((document.createElement("a")));
                      ((btn.textContent = "Create"));
                      ((btn.href = url));
                      ((btn.target = "_blank"));
                      ((btn.style.cssText = "background:" + color + ";color:white;text-decoration:none;padding:6px 14px;border-radius:6px;font-size:12px;font-weight:600;transition:transform 0.2s;"));
                      ((btn.onmouseenter = () => { btn.style.transform = 'scale(1.05)'; }));
                      ((btn.onmouseleave = () => { btn.style.transform = 'scale(1)'; }));
                      ((item.appendChild(label)));
                      ((item.appendChild(btn)));
                      ((panel.appendChild(item)));
                    }));
      }
      
    };
    renderCategory("Critical", critical, "#f44336");
    renderCategory("Important", important, "#ff9800");
    renderCategory("Recommended", recommended, "#2196f3");
    ((document.createElement("div")));
    ((footer.innerHTML = "<div style='margin-top:15px;padding-top:15px;border-top:1px solid #333;font-size:11px;color:#666;text-align:center;'>Powered by <a href='https://github.com/hyperpolymath/grimrepo-scripts' style='color:#2196f3;text-decoration:none;'>GrimRepo-Scripts</a></div>"));
    ((panel.appendChild(footer)));
  }
  ((document.body.appendChild(panel)));
}

var UI = {
  createPanel: createPanel
};

function init() {
  console.log("🎨 GrimTemplateEngine v" + METADATA_VERSION + " - Repository Health Agent");
  var info = scan();
  if (info !== undefined) {
    console.log("✓ Detected: " + info.owner + "/" + info.name + " on " + name(info.platform));
    var missing = Belt_Array.keep(all, (function (std) {
            return !hasFile(std.filename, info);
          }));
    console.log("📊 Health Score: " + String(calculateScore(missing)) + "/100");
    console.log("📄 Missing " + String(missing.length) + " files");
    return createPanel(missing, info);
  }
  console.log("ℹ️ No repository detected in current page");
}

init();

export {
  Platform ,
  Context ,
  Templates ,
  Standards ,
  URLGenerator ,
  $$Storage ,
  UI ,
  init ,
}
/*  Not a pure module */
