// ==UserScript==
// @name         GrimSecurityScanner
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  Security vulnerability detector for repositories
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://github.com/*/*
// @match        *://gitlab.com/*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @grant        GM.xmlHttpRequest
// @grant        GM.registerMenuCommand
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

let secretPatterns = [
  [
    "api[_-]?key",
    "API key"
  ],
  [
    "secret[_-]?key",
    "secret key"
  ],
  [
    "password\\s*=",
    "hardcoded password"
  ],
  [
    "token\\s*=",
    "authentication token"
  ],
  [
    "private[_-]?key",
    "private key"
  ],
  [
    "[a-z0-9]{32,}",
    "potential hash/key"
  ],
  [
    "ghp_[a-zA-Z0-9]{36}",
    "GitHub Personal Access Token"
  ],
  [
    "sk_live_[a-zA-Z0-9]{24,}",
    "Stripe secret key"
  ],
  [
    "AKIA[0-9A-Z]{16}",
    "AWS Access Key"
  ]
];

let dangerousPatterns = [
  [
    "eval\\(",
    "Use of eval()"
  ],
  [
    "exec\\(",
    "Use of exec()"
  ],
  [
    "system\\(",
    "System command execution"
  ],
  [
    "innerHTML\\s*=",
    "Potential XSS via innerHTML"
  ],
  [
    "document\\.write",
    "Use of document.write"
  ],
  [
    "dangerouslySetInnerHTML",
    "React dangerouslySetInnerHTML"
  ]
];

let insecureDependencies = [
  [
    "\"lodash\":\\s*\"<4\\.17\\.21\"",
    "Lodash < 4.17.21"
  ],
  [
    "\"axios\":\\s*\"<0\\.21\\.1\"",
    "Axios < 0.21.1"
  ],
  [
    "\"moment\":\\s*\".*\"",
    "Moment.js (deprecated)"
  ]
];

function detectSecrets(content, filename) {
  let issues = [];
  Belt_Array.forEach(secretPatterns, param => {
    ((new RegExp(pattern, "gi")));
    if ((regex.test(content))) {
      return (issues.push(issue));
    }
  });
  return issues;
}

function detectDangerousCode(content, filename) {
  let issues = [];
  Belt_Array.forEach(dangerousPatterns, param => {
    ((new RegExp(pattern, "g")));
    if ((regex.test(content))) {
      return (issues.push(issue));
    }
  });
  return issues;
}

function checkSecurityFiles() {
  let hasSecurityMd = Belt_Option.isSome(GrimCore.DOM.query("a[title='SECURITY.md']"));
  let hasCodeOfConduct = Belt_Option.isSome(GrimCore.DOM.query("a[title='CODE_OF_CONDUCT.md']"));
  return [
    hasSecurityMd,
    hasCodeOfConduct
  ];
}

function calculateRiskScore(result) {
  let score = 0;
  score = score + (result.highSeverity * 30 | 0) | 0;
  score = score + (result.mediumSeverity * 15 | 0) | 0;
  score = score + (result.lowSeverity * 5 | 0) | 0;
  if (!result.hasSecurityMd) {
    score = score + 10 | 0;
  }
  if (!result.hasCodeOfConduct) {
    score = score + 5 | 0;
  }
  return score;
}

function scanRepository() {
  let issues = [];
  let match = checkSecurityFiles();
  let hasCodeOfConduct = match[1];
  let hasSecurityMd = match[0];
  if (!hasSecurityMd) {
    ((issues.push(issue)));
  }
  if (!hasCodeOfConduct) {
    ((issues.push(issue)));
  }
  let highCount = {
    contents: 0
  };
  let mediumCount = {
    contents: 0
  };
  let lowCount = {
    contents: 0
  };
  Belt_Array.forEach(issues, issue => {
    let match = issue.severity;
    switch (match) {
      case "High" :
        highCount.contents = highCount.contents + 1 | 0;
        return;
      case "Medium" :
        mediumCount.contents = mediumCount.contents + 1 | 0;
        return;
      case "Low" :
        lowCount.contents = lowCount.contents + 1 | 0;
        return;
    }
  });
  let result_totalIssues = issues.length;
  let result_highSeverity = highCount.contents;
  let result_mediumSeverity = mediumCount.contents;
  let result_lowSeverity = lowCount.contents;
  let result = {
    totalIssues: result_totalIssues,
    highSeverity: result_highSeverity,
    mediumSeverity: result_mediumSeverity,
    lowSeverity: result_lowSeverity,
    issues: issues,
    hasSecurityMd: hasSecurityMd,
    hasCodeOfConduct: hasCodeOfConduct,
    riskScore: 0
  };
  let riskScore = calculateRiskScore(result);
  return {
    totalIssues: result_totalIssues,
    highSeverity: result_highSeverity,
    mediumSeverity: result_mediumSeverity,
    lowSeverity: result_lowSeverity,
    issues: issues,
    hasSecurityMd: hasSecurityMd,
    hasCodeOfConduct: hasCodeOfConduct,
    riskScore: riskScore
  };
}

let css = `
.grim-security-panel {
  position: fixed;
  top: 80px;
  right: 20px;
  width: 400px;
  max-height: 600px;
  overflow-y: auto;
  background: linear-gradient(135deg, #4a1a1a 0%, #1a1a2e 100%);
  border: 1px solid #7a4a4a;
  border-radius: 8px;
  padding: 20px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
  color: #e0e0e0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  z-index: 10000;
}

.grim-security-header {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 15px;
  color: #f44336;
}

.grim-security-score {
  text-align: center;
  padding: 15px;
  margin-bottom: 15px;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.05);
}

.grim-security-score-value {
  font-size: 36px;
  font-weight: 700;
  margin-bottom: 5px;
}

.grim-security-score-label {
  font-size: 11px;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 1px;
}

.grim-security-stats {
  display: flex;
  gap: 10px;
  margin-bottom: 15px;
}

.grim-security-stat {
  flex: 1;
  text-align: center;
  padding: 10px;
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.05);
}

.grim-security-stat-value {
  font-size: 24px;
  font-weight: 700;
}

.grim-security-stat-label {
  font-size: 10px;
  color: #999;
  text-transform: uppercase;
  margin-top: 4px;
}

.grim-security-stat.high .grim-security-stat-value {
  color: #f44336;
}

.grim-security-stat.medium .grim-security-stat-value {
  color: #ff9800;
}

.grim-security-stat.low .grim-security-stat-value {
  color: #2196f3;
}

.grim-security-issue {
  padding: 10px;
  margin-bottom: 8px;
  border-left: 3px solid;
  border-radius: 4px;
  background: rgba(255, 255, 255, 0.05);
}

.grim-security-issue.high {
  border-color: #f44336;
}

.grim-security-issue.medium {
  border-color: #ff9800;
}

.grim-security-issue.low {
  border-color: #2196f3;
}

.grim-security-issue-category {
  font-size: 10px;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 1px;
}

.grim-security-issue-desc {
  font-size: 13px;
  font-weight: 600;
  margin: 4px 0;
}

.grim-security-issue-remediation {
  font-size: 11px;
  color: #999;
  font-style: italic;
}

.grim-security-close {
  position: absolute;
  top: 10px;
  right: 10px;
  background: none;
  border: none;
  color: #999;
  font-size: 24px;
  cursor: pointer;
  width: 30px;
  height: 30px;
  line-height: 1;
  padding: 0;
}

.grim-security-close:hover {
  color: #fff;
}
`;

function severityToClass(sev) {
  switch (sev) {
    case "High" :
      return "high";
    case "Medium" :
      return "medium";
    case "Low" :
      return "low";
  }
}

function createPanel(result) {
  GrimCore.DOM.create("div", "grim-security-panel", undefined);
  Belt_Array.map(Belt_Array.slice(result.issues, 0, 15), issue => {
    let sevClass = severityToClass(issue.severity);
    return `<div class="grim-security-issue ` + sevClass + `">
          <div class="grim-security-issue-category">` + issue.category + `</div>
          <div class="grim-security-issue-desc">` + issue.description + `</div>
          <div class="grim-security-issue-remediation">` + issue.remediation + `</div>
        </div>`;
  }).join("");
  ((panel.innerHTML = "<div class='grim-security-header'>Security Scan</div>" +
    "<div class='grim-security-score'><div class='grim-security-score-value' style='color:" + riskColor + "'>" + result.riskScore + "</div><div class='grim-security-score-label'>Risk Score</div></div>" +
    "<div class='grim-security-stats'><div class='grim-security-stat high'><div class='grim-security-stat-value'>" + result.highSeverity + "</div><div class='grim-security-stat-label'>High</div></div>" +
    "<div class='grim-security-stat medium'><div class='grim-security-stat-value'>" + result.mediumSeverity + "</div><div class='grim-security-stat-label'>Medium</div></div>" +
    "<div class='grim-security-stat low'><div class='grim-security-stat-value'>" + result.lowSeverity + "</div><div class='grim-security-stat-label'>Low</div></div></div>" +
    issuesList));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.className = "grim-security-close"));
  ((closeBtn.onclick = () => panel.remove()));
  ((panel.appendChild(closeBtn)));
  ((document.body.appendChild(panel)));
}

function run() {
  GrimCore.Log.info("GrimSecurityScanner running");
  GM_addStyle(css);
  createPanel(scanRepository());
}

if (GrimCore.URL.isGitHub() || GrimCore.URL.isGitLab()) {
  GM_registerMenuCommand("Run Security Scan", () => run());
}

export {
  secretPatterns,
  dangerousPatterns,
  insecureDependencies,
  detectSecrets,
  detectDangerousCode,
  checkSecurityFiles,
  calculateRiskScore,
  scanRepository,
  css,
  severityToClass,
  createPanel,
  run,
}
/*  Not a pure module */
