// ==UserScript==
// @name         GrimLicenseChecker
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  License compliance validator with SPDX header detection
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://github.com/*/*
// @match        *://gitlab.com/*/*
// @match        *://bitbucket.org/*/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @grant        GM.xmlHttpRequest
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as GrimCore from "../../core/GrimCore.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var supportedExtensions = [
  ".res",
  ".resi",
  ".js",
  ".ts",
  ".tsx",
  ".jsx",
  ".rs",
  ".ml",
  ".mli",
  ".jl",
  ".ex",
  ".exs",
  ".gleam",
  ".scm",
  ".sh",
  ".bash",
  ".yml",
  ".yaml"
];

var spdxPatterns = [
  [
    "PMPL-1\\.0(?:-or-later)?",
    "PMPL_1_0"
  ],
  [
    "MPL-2\\.0",
    "MPL_2_0"
  ],
  [
    "MIT",
    "MIT"
  ],
  [
    "Apache-2\\.0",
    "Apache_2_0"
  ],
  [
    "GPL-3\\.0",
    "GPL_3_0"
  ],
  [
    "AGPL-3\\.0",
    "AGPL_3_0"
  ],
  [
    "BSD-3-Clause",
    "BSD_3Clause"
  ]
];

function licenseToString(lic) {
  if (typeof lic === "object") {
    return "Unknown (" + lic._0 + ")";
  }
  switch (lic) {
    case "PMPL_1_0" :
        return "PMPL-1.0-or-later";
    case "MPL_2_0" :
        return "MPL-2.0";
    case "MIT" :
        return "MIT";
    case "Apache_2_0" :
        return "Apache-2.0";
    case "GPL_3_0" :
        return "GPL-3.0";
    case "AGPL_3_0" :
        return "AGPL-3.0";
    case "BSD_3Clause" :
        return "BSD-3-Clause";
    
  }
}

function parseSPDX(content) {
  if (!content.includes("SPDX-License-Identifier:")) {
    return "Missing";
  }
  var found = Belt_Array.reduce(spdxPatterns, undefined, (function (acc, param) {
          if (acc !== undefined) {
            return acc;
          } else {
            ((new RegExp(pattern, "i")));
            if ((regex.test(content))) {
              return param[1];
            } else {
              return ;
            }
          }
        }));
  if (found !== undefined) {
    return {
            TAG: "Present",
            _0: found
          };
  } else {
    return {
            TAG: "Invalid",
            _0: "Unrecognized SPDX identifier"
          };
  }
}

function shouldCheckFile(path) {
  return Belt_Array.some(supportedExtensions, (function (ext) {
                return path.endsWith(ext);
              }));
}

async function fetchFileContent(url) {
  try {
    var resp = await GrimCore.HTTP.$$fetch(undefined, undefined, url);
    if (resp.status === 200) {
      return resp.responseText;
    } else {
      return ;
    }
  }
  catch (exn){
    return ;
  }
}

function getFileListFromPage() {
  var links = GrimCore.DOM.queryAll("a[href*='/blob/']");
  return Belt_Array.slice(Belt_Array.keep(Belt_Array.map(links, (function (link) {
                        return (link.getAttribute('href'));
                      })), (function (href) {
                    var path = Belt_Option.getWithDefault(Belt_Array.get(href.split("/blob/"), 1), "");
                    return shouldCheckFile(path);
                  })), 0, 50);
}

async function scanRepository(repoUrl) {
  var files = getFileListFromPage();
  var filesChecked = 0;
  var filesWithHeaders = 0;
  var detectedLicenses = [];
  var allChecks = [];
  for(var i = 0 ,i_finish = files.length; i < i_finish; ++i){
    var file = Belt_Array.get(files, i);
    if (file !== undefined) {
      var rawUrl = file.replace(/\/blob\//, "/raw/");
      var content = await fetchFileContent(rawUrl);
      if (content !== undefined) {
        filesChecked = filesChecked + 1 | 0;
        var status = parseSPDX(content);
        if (typeof status === "object" && status.TAG === "Present") {
          var lic = status._0;
          filesWithHeaders = filesWithHeaders + 1 | 0;
          if (!Belt_Array.some(detectedLicenses, (function(lic){
                return function (l) {
                  return Caml_obj.equal(l, lic);
                }
                }(lic)))) {
            detectedLicenses = Belt_Array.concat(detectedLicenses, [lic]);
          }
          
        }
        var check = {
          path: file,
          spdxStatus: status,
          hasLicenseFile: false
        };
        allChecks = Belt_Array.concat(allChecks, [check]);
      }
      
    }
    
  }
  return {
          totalFiles: filesChecked,
          filesWithHeaders: filesWithHeaders,
          filesMissingHeaders: filesChecked - filesWithHeaders | 0,
          detectedLicenses: detectedLicenses,
          inconsistentLicenses: detectedLicenses.length > 1,
          checks: allChecks
        };
}

var css = "\n.grim-license-panel {\n  position: fixed;\n  top: 80px;\n  right: 20px;\n  width: 360px;\n  max-height: 600px;\n  overflow-y: auto;\n  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);\n  border: 1px solid #3a3a5c;\n  border-radius: 8px;\n  padding: 20px;\n  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);\n  color: #e0e0e0;\n  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n  z-index: 10000;\n}\n\n.grim-license-header {\n  font-size: 18px;\n  font-weight: 600;\n  margin-bottom: 15px;\n  color: #4CAF50;\n}\n\n.grim-license-stat {\n  display: flex;\n  justify-content: space-between;\n  padding: 8px 0;\n  border-bottom: 1px solid #2a2a3e;\n}\n\n.grim-license-stat:last-child {\n  border-bottom: none;\n}\n\n.grim-license-label {\n  color: #999;\n  font-size: 13px;\n}\n\n.grim-license-value {\n  color: #fff;\n  font-weight: 600;\n  font-size: 14px;\n}\n\n.grim-license-warning {\n  background: #ff9800;\n  color: #000;\n  padding: 10px;\n  border-radius: 6px;\n  margin-top: 15px;\n  font-size: 12px;\n  font-weight: 600;\n}\n\n.grim-license-success {\n  background: #4CAF50;\n  color: #000;\n  padding: 10px;\n  border-radius: 6px;\n  margin-top: 15px;\n  font-size: 12px;\n  font-weight: 600;\n}\n\n.grim-license-close {\n  position: absolute;\n  top: 10px;\n  right: 10px;\n  background: none;\n  border: none;\n  color: #999;\n  font-size: 24px;\n  cursor: pointer;\n  width: 30px;\n  height: 30px;\n  line-height: 1;\n  padding: 0;\n}\n\n.grim-license-close:hover {\n  color: #fff;\n}\n\n.grim-license-file-list {\n  margin-top: 15px;\n  max-height: 300px;\n  overflow-y: auto;\n}\n\n.grim-license-file {\n  padding: 6px;\n  font-size: 11px;\n  font-family: monospace;\n  border-left: 3px solid;\n  margin-bottom: 4px;\n  background: rgba(255,255,255,0.05);\n}\n\n.grim-license-file.missing {\n  border-color: #f44336;\n}\n\n.grim-license-file.present {\n  border-color: #4CAF50;\n}\n";

function createPanel(result) {
  GrimCore.DOM.create("div", "grim-license-panel", undefined);
  Belt_Array.map(result.detectedLicenses, licenseToString).join(", ");
  Belt_Array.map(Belt_Array.slice(result.checks, 0, 20), (function (check) {
            var match = check.spdxStatus;
            var statusClass;
            statusClass = typeof match !== "object" || match.TAG !== "Present" ? "missing" : "present";
            var filename = Belt_Option.getWithDefault(Belt_Array.get(Belt_Array.reverse(check.path.split("/")), 0), check.path);
            return "<div class=\"grim-license-file " + statusClass + "\">" + filename + "</div>";
          })).join("");
  ((panel.innerHTML = "<div class='grim-license-header'>License Compliance</div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Files Scanned</span><span class='grim-license-value'>" + result.totalFiles + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>With SPDX Headers</span><span class='grim-license-value'>" + result.filesWithHeaders + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Missing Headers</span><span class='grim-license-value'>" + result.filesMissingHeaders + "</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Compliance Rate</span><span class='grim-license-value'>" + complianceRate + "%</span></div>" +
    "<div class='grim-license-stat'><span class='grim-license-label'>Detected Licenses</span><span class='grim-license-value'>" + detectedLics + "</span></div>" +
    statusMsg +
    "<div class='grim-license-file-list'>" + fileList + "</div>"));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.className = "grim-license-close"));
  ((closeBtn.onclick = () => panel.remove()));
  ((panel.appendChild(closeBtn)));
  ((document.body.appendChild(panel)));
}

async function run() {
  GrimCore.Log.info("GrimLicenseChecker running");
  GM_addStyle(css);
  var url = location.href;
  var result = await scanRepository(url);
  return createPanel(result);
}

if (GrimCore.$$URL.isGitHub() || GrimCore.$$URL.isGitLab()) {
  run();
}

export {
  supportedExtensions ,
  spdxPatterns ,
  licenseToString ,
  parseSPDX ,
  shouldCheckFile ,
  fetchFileContent ,
  getFileListFromPage ,
  scanRepository ,
  css ,
  createPanel ,
  run ,
}
/*  Not a pure module */
