// ==UserScript==
// @name         GrimCIValidator
// @namespace    https://github.com/hyperpolymath
// @version      1.0.0
// @description  GitHub Actions workflow quality checker
// @author       Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
// @homepage     https://github.com/hyperpolymath/grimrepo-scripts
// @supportURL   https://github.com/hyperpolymath/grimrepo-scripts/issues
// @match        *://github.com/*/.github/workflows/*
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.addStyle
// @license      PMPL-1.0-or-later
// @run-at       document-end
// ==/UserScript==

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function checkPermissions(content) {
  return content.includes("permissions:");
}

function checkSPDXHeader(content) {
  return content.includes("SPDX-License-Identifier:");
}

function findUnpinnedActions(content) {
  var lines = content.split("\n");
  var unpinned = [];
  Belt_Array.forEach(lines, (function (line) {
          if (line.includes("uses:") && Belt_Option.isSome(Caml_option.null_to_opt(line.match(/@[a-z0-9\\.\\-]+$/i)))) {
            line.replace("uses:", "").trim();
            return (unpinned.push(action));
          }
          
        }));
  return unpinned;
}

function detectIssues(content) {
  var issues = [];
  if (!content.includes("permissions:")) {
    ((issues.push(issue)));
  }
  if (!content.includes("SPDX-License-Identifier:")) {
    ((issues.push(issue)));
  }
  var unpinned = findUnpinnedActions(content);
  if (unpinned.length !== 0) {
    Belt_Array.forEach(unpinned, (function (action) {
            ((issues.push(issue)));
          }));
  }
  if (Belt_Option.isSome(Caml_option.null_to_opt(content.match(/password|token|key|secret/i))) && !content.includes("secrets.")) {
    ((issues.push(issue)));
  }
  return issues;
}

function calculateScore(result) {
  var deductions = {
    contents: 0
  };
  if (!result.hasPermissions) {
    deductions.contents = deductions.contents + 30 | 0;
  }
  if (!result.hasSPDXHeader) {
    deductions.contents = deductions.contents + 10 | 0;
  }
  deductions.contents = deductions.contents + Math.imul(result.unpinnedActions.length, 15) | 0;
  Belt_Array.forEach(result.issues, (function (issue) {
          var match = issue.level;
          switch (match) {
            case "Critical" :
                deductions.contents = deductions.contents + 20 | 0;
                return ;
            case "Warning" :
                deductions.contents = deductions.contents + 10 | 0;
                return ;
            case "Info" :
                deductions.contents = deductions.contents + 5 | 0;
                return ;
            
          }
        }));
  return Math.max(0, 100 - deductions.contents | 0);
}

function validateWorkflow(content) {
  var hasPermissions = content.includes("permissions:");
  var hasSPDXHeader = content.includes("SPDX-License-Identifier:");
  var unpinnedActions = findUnpinnedActions(content);
  var issues = detectIssues(content);
  var result = {
    hasPermissions: hasPermissions,
    hasSPDXHeader: hasSPDXHeader,
    unpinnedActions: unpinnedActions,
    issues: issues,
    score: 0
  };
  var score = calculateScore(result);
  return {
          hasPermissions: hasPermissions,
          hasSPDXHeader: hasSPDXHeader,
          unpinnedActions: unpinnedActions,
          issues: issues,
          score: score
        };
}

var css = "\n.grim-ci-panel {\n  position: fixed;\n  top: 80px;\n  right: 20px;\n  width: 380px;\n  max-height: 600px;\n  overflow-y: auto;\n  background: linear-gradient(135deg, #2c1a4d 0%, #1a1a2e 100%);\n  border: 1px solid #5a4a7c;\n  border-radius: 8px;\n  padding: 20px;\n  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);\n  color: #e0e0e0;\n  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n  z-index: 10000;\n}\n\n.grim-ci-header {\n  font-size: 18px;\n  font-weight: 600;\n  margin-bottom: 15px;\n  color: #9c27b0;\n}\n\n.grim-ci-score {\n  text-align: center;\n  padding: 15px;\n  margin-bottom: 15px;\n  border-radius: 8px;\n  background: rgba(255, 255, 255, 0.05);\n}\n\n.grim-ci-score-value {\n  font-size: 36px;\n  font-weight: 700;\n  margin-bottom: 5px;\n}\n\n.grim-ci-score-label {\n  font-size: 11px;\n  color: #999;\n  text-transform: uppercase;\n  letter-spacing: 1px;\n}\n\n.grim-ci-issue {\n  padding: 10px;\n  margin-bottom: 8px;\n  border-left: 3px solid;\n  border-radius: 4px;\n  background: rgba(255, 255, 255, 0.05);\n}\n\n.grim-ci-issue.critical {\n  border-color: #f44336;\n}\n\n.grim-ci-issue.warning {\n  border-color: #ff9800;\n}\n\n.grim-ci-issue.info {\n  border-color: #2196f3;\n}\n\n.grim-ci-issue-message {\n  font-size: 13px;\n  font-weight: 600;\n  margin-bottom: 4px;\n}\n\n.grim-ci-issue-suggestion {\n  font-size: 11px;\n  color: #999;\n  font-style: italic;\n}\n\n.grim-ci-close {\n  position: absolute;\n  top: 10px;\n  right: 10px;\n  background: none;\n  border: none;\n  color: #999;\n  font-size: 24px;\n  cursor: pointer;\n  width: 30px;\n  height: 30px;\n  line-height: 1;\n  padding: 0;\n}\n\n.grim-ci-close:hover {\n  color: #fff;\n}\n";

function levelToClass(level) {
  switch (level) {
    case "Critical" :
        return "critical";
    case "Warning" :
        return "warning";
    case "Info" :
        return "info";
    
  }
}

function createPanel(result) {
  GrimCore.DOM.create("div", "grim-ci-panel", undefined);
  Belt_Array.map(result.issues, (function (issue) {
            var levelClass = levelToClass(issue.level);
            return "<div class=\"grim-ci-issue " + levelClass + "\">\n          <div class=\"grim-ci-issue-message\">" + issue.message + "</div>\n          <div class=\"grim-ci-issue-suggestion\">" + issue.suggestion + "</div>\n        </div>";
          })).join("");
  ((panel.innerHTML = "<div class='grim-ci-header'>CI/CD Quality Check</div>" +
    "<div class='grim-ci-score'><div class='grim-ci-score-value' style='color:" + scoreColor + "'>" + result.score + "</div><div class='grim-ci-score-label'>Workflow Score</div></div>" +
    issuesList));
  ((document.createElement("button")));
  ((closeBtn.textContent = "×"));
  ((closeBtn.className = "grim-ci-close"));
  ((closeBtn.onclick = () => panel.remove()));
  ((panel.appendChild(closeBtn)));
  ((document.body.appendChild(panel)));
}

function run() {
  GrimCore.Log.info("GrimCIValidator running");
  GM_addStyle(css);
  var codeBlock = GrimCore.DOM.query("pre code, .blob-code-inner");
  if (codeBlock === undefined) {
    return GrimCore.Log.warn("Could not find workflow content");
  }
  var content = (el.textContent || el.innerText);
  var result = validateWorkflow(content);
  createPanel(result);
}

if (GrimCore.$$URL.isGitHub() && location.href.includes("/.github/workflows/")) {
  run();
}

export {
  checkPermissions ,
  checkSPDXHeader ,
  findUnpinnedActions ,
  detectIssues ,
  calculateScore ,
  validateWorkflow ,
  css ,
  levelToClass ,
  createPanel ,
  run ,
}
/*  Not a pure module */
