// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimGreaser from "./GrimGreaser.mjs";

async function main() {
  console.log("🚀 Custom Build Script");
  return await GrimGreaser.buildScript("src/scripts/example/MyScript.bs.js", "dist/MyScript.user.js", true);
}

main();

export {
  main,
}
/*  Not a pure module */
