// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Esbuild from "esbuild";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function parseConfig(jsonStr) {
  try {
    let json = JSON.parse(jsonStr);
    let obj = Belt_Option.getExn(Js_json.decodeObject(json));
    let name = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "name"), Js_json.decodeString));
    let version = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "version"), Js_json.decodeString));
    let license = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "license"), Js_json.decodeString));
    let userScriptObj = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "userScript"), Js_json.decodeObject));
    let namespace = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "namespace"), Js_json.decodeString));
    let description = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "description"), Js_json.decodeString));
    let match = Belt_Option.getExn(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(userScriptObj, "match"), Js_json.decodeArray), arr => Belt_Array.keepMap(arr, Js_json.decodeString)));
    let grant = Belt_Option.getExn(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(userScriptObj, "grant"), Js_json.decodeArray), arr => Belt_Array.keepMap(arr, Js_json.decodeString)));
    let runAt = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(userScriptObj, "runAt"), Js_json.decodeString));
    return {
      name: name,
      version: version,
      license: license,
      userScript: {
        namespace: namespace,
        description: description,
        match: match,
        grant: grant,
        runAt: runAt
      }
    };
  } catch (exn) {
    return;
  }
}

function generateHeader(config) {
  let matchLines = Belt_Array.map(config.userScript.match, url => `// @match       ` + url).join("\n");
  let grantLines = Belt_Array.map(config.userScript.grant, perm => `// @grant       ` + perm).join("\n");
  return `// ==UserScript==
// @name        ` + config.name + `
// @namespace   ` + config.userScript.namespace + `
// @version     ` + config.version + `
// @description ` + config.userScript.description + `
// @license     ` + config.license + `
` + matchLines + `
` + grantLines + `
// @run-at      ` + config.userScript.runAt + `
// @noframes
// ==/UserScript==

`;
}

async function buildScript(entry, output, minifyOpt) {
  let minify = minifyOpt !== undefined ? minifyOpt : false;
  console.log("🔸 [ReGrease] Starting Pure ReScript Build...");
  let configPath = Deno.cwd() + `/deno.json`;
  let configStr = await Deno.readTextFile(configPath);
  let c = parseConfig(configStr);
  let config = c !== undefined ? c : (console.error("❌ Failed to parse deno.json"), Deno.exit(1), Stdlib_Exn.raiseError("Config parse failed"));
  console.log(`🔹 Building: ` + config.name + ` v` + config.version);
  let header = generateHeader(config);
  let bannerDict = {};
  bannerDict["js"] = header;
  let defineDict = {};
  defineDict["METADATA_VERSION"] = `"` + config.version + `"`;
  defineDict["METADATA_NAME"] = `"` + config.name + `"`;
  try {
    await Esbuild.build({
      entryPoints: [entry],
      bundle: true,
      outfile: output,
      banner: bannerDict,
      define: defineDict,
      format: "iife",
      minify: minify,
      target: "es2020"
    });
    console.log(`✅ Build Complete: ` + output);
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    console.error("❌ Build Failed:");
    console.error(exn);
    Deno.exit(1);
  }
  Esbuild.stop();
}

async function run() {
  return await buildScript("src/Main.bs.js", "dist/userscript.user.js", false);
}

run();

export {
  parseConfig,
  generateHeader,
  buildScript,
  run,
}
/*  Not a pure module */
