// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let Fs = {};

let Path = {};

let distDir = "./dist";

if (!Nodefs.existsSync(distDir)) {
  Nodefs.mkdirSync(distDir, {
    recursive: true
  });
}

let scripts = [
  {
    name: "GrimGreaser",
    entry: "./src/scripts/greaser/GrimGreaser.res.mjs",
    metadata: {
      name: "GrimGreaser",
      version: "1.0.0",
      description: "Pure ReScript build system with GreasyFork auto-publish",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: [
        "*://github.com/*/*",
        "*://gitlab.com/*/*"
      ],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle",
        "GM.xmlHttpRequest"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  },
  {
    name: "GrimPager",
    entry: "./src/scripts/pager/GrimPager.res.mjs",
    metadata: {
      name: "GrimPager",
      version: "1.0.0",
      description: "Perpetual auto-paging engine with smart detection",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: ["*://*/*"],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  },
  {
    name: "GrimTemplateEngine",
    entry: "./src/scripts/template/GrimTemplateEngine.res.mjs",
    metadata: {
      name: "GrimTemplateEngine",
      version: "1.0.0",
      description: "Intelligent repository health agent with context-aware templates",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: [
        "*://github.com/*/*",
        "*://gitlab.com/*/*",
        "*://bitbucket.org/*/*",
        "*://codeberg.org/*/*",
        "*://sr.ht/*/*"
      ],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  },
  {
    name: "GrimLicenseChecker",
    entry: "./src/scripts/license/GrimLicenseChecker.res.mjs",
    metadata: {
      name: "GrimLicenseChecker",
      version: "1.0.0",
      description: "License compliance validator with SPDX header detection",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: [
        "*://github.com/*/*",
        "*://gitlab.com/*/*",
        "*://bitbucket.org/*/*"
      ],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle",
        "GM.xmlHttpRequest"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  },
  {
    name: "GrimCIValidator",
    entry: "./src/scripts/ci/GrimCIValidator.res.mjs",
    metadata: {
      name: "GrimCIValidator",
      version: "1.0.0",
      description: "GitHub Actions workflow quality checker",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: ["*://github.com/*/.github/workflows/*"],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  },
  {
    name: "GrimSecurityScanner",
    entry: "./src/scripts/security/GrimSecurityScanner.res.mjs",
    metadata: {
      name: "GrimSecurityScanner",
      version: "1.0.0",
      description: "Security vulnerability detector for repositories",
      author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
      namespace: "https://github.com/hyperpolymath",
      homepage: "https://github.com/hyperpolymath/grimrepo-scripts",
      supportURL: "https://github.com/hyperpolymath/grimrepo-scripts/issues",
      match: [
        "*://github.com/*/*",
        "*://gitlab.com/*/*"
      ],
      grant: [
        "GM.getValue",
        "GM.setValue",
        "GM.addStyle",
        "GM.xmlHttpRequest",
        "GM.registerMenuCommand"
      ],
      license: "MPL-2.0",
      runAt: "document-end"
    }
  }
];

function generateMetadataBlock(metadata) {
  let lines = [
    "// ==UserScript==",
    `// @name         ` + metadata.name,
    `// @namespace    ` + metadata.namespace,
    `// @version      ` + metadata.version,
    `// @description  ` + metadata.description,
    `// @author       ` + metadata.author,
    `// @homepage     ` + metadata.homepage,
    `// @supportURL   ` + metadata.supportURL
  ];
  metadata.match.forEach(pattern => {
    lines.push(`// @match        ` + pattern);
  });
  metadata.grant.forEach(grant => {
    lines.push(`// @grant        ` + grant);
  });
  lines.push(`// @license      ` + metadata.license);
  lines.push(`// @run-at       ` + metadata.runAt);
  lines.push("// ==/UserScript==");
  lines.push("");
  return lines.join("\n");
}

console.log("Building userscripts...\n");

scripts.forEach(script => {
  try {
    let code = Nodefs.readFileSync(script.entry, "utf-8");
    let header = generateMetadataBlock(script.metadata);
    let output = header + "\n" + code;
    let outputPath = Nodepath.join(distDir, script.name + `.user.js`);
    Nodefs.writeFileSync(outputPath, output, "utf-8");
    console.log(`✓ Built ` + script.name + `.user.js`);
    return;
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    console.error(`✗ Failed to build ` + script.name + `:`, exn);
    return;
  }
});

console.log(`\nAll userscripts built in ` + distDir + `/`);

console.log("\nTo publish to GreasyFork:");

console.log("1. Visit https://greasyfork.org/en/scripts/new");

console.log("2. Upload each .user.js file");

console.log("3. Fill in description and set language to 'English'");

console.log("4. Click 'Post script'");

export {
  Fs,
  Path,
  distDir,
  scripts,
  generateMetadataBlock,
}
/*  Not a pure module */
