// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

let $$Deno = {};

let apiBase = "https://greasyfork.org/api/v1";

let scripts = [
  "GrimGreaser",
  "GrimPager",
  "GrimTemplateEngine",
  "GrimLicenseChecker",
  "GrimCIValidator",
  "GrimSecurityScanner"
];

async function publishScript(name, apiKey) {
  let code = await Deno.readTextFile(`./dist/` + name + `.user.js`);
  let formData = new FormData();
  formData.append("code", code);
  formData.append("locale", "en");
  let response = await fetch(apiBase + `/scripts`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ` + apiKey
    },
    body: formData
  });
  if (response.ok) {
    let result = await response.json();
    console.log(`✓ Published ` + name + ` - ID: ` + result.id.toString());
    console.log(`  URL: https://greasyfork.org/en/scripts/` + result.id.toString());
    return result.id;
  }
  let error = await response.text();
  console.error(`✗ Failed to publish ` + name + `:`, error);
}

async function updateScript(scriptId, name, apiKey) {
  let code = await Deno.readTextFile(`./dist/` + name + `.user.js`);
  let formData = new FormData();
  formData.append("code", code);
  formData.append("changelog", "Initial release");
  let response = await fetch(apiBase + `/scripts/` + scriptId.toString() + `/versions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ` + apiKey
    },
    body: formData
  });
  if (response.ok) {
    console.log(`✓ Updated ` + name);
    return true;
  }
  let error = await response.text();
  console.error(`✗ Failed to update ` + name + `:`, error);
  return false;
}

async function main() {
  let apiKeyOpt = Deno.env.get("GREASYFORK_API_KEY");
  if (apiKeyOpt !== undefined) {
    console.log("Publishing to GreasyFork...\n");
    for (let i = 0, i_finish = scripts.length; i < i_finish; ++i) {
      let name = Belt_Array.getExn(scripts, i);
      await publishScript(name, apiKeyOpt);
      await new Promise((resolve, _reject) => {
        setTimeout(() => resolve(), 2000);
      });
    }
    console.log("\n✓ All scripts published!");
    console.log("\nNext steps:");
    console.log("1. Check https://greasyfork.org/en/users/scripts");
    console.log("2. Add screenshots to each script");
    console.log("3. Add detailed descriptions");
    console.log("4. Set appropriate tags");
    return;
  }
  console.log("⚠️  GREASYFORK_API_KEY not set");
  console.log("\nTo get your API key:");
  console.log("1. Log in to https://greasyfork.org");
  console.log("2. Go to https://greasyfork.org/en/users/edit");
  console.log("3. Scroll to 'API' section");
  console.log("4. Copy your API key");
  console.log("\nThen run:");
  console.log("  export GREASYFORK_API_KEY=your_key_here");
  console.log("  deno run --allow-read --allow-net --allow-env publish-greasyfork.res.mjs");
  console.log("\n=== OR MANUAL UPLOAD ===");
  console.log("\nFor each file in dist/:");
  scripts.forEach(script => {
    console.log(`\n` + script + `.user.js:`);
    console.log(`  1. Visit https://greasyfork.org/en/scripts/new`);
    console.log(`  2. Click 'Choose File' and select dist/` + script + `.user.js`);
    console.log(`  3. Set language to 'English'`);
    console.log(`  4. Click 'Post script'`);
  });
  return Deno.exit(1);
}

main();

export {
  $$Deno,
  apiBase,
  scripts,
  publishScript,
  updateScript,
  main,
}
/*  Not a pure module */
