// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Js_promise from "@rescript/runtime/lib/es6/Js_promise.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

let scriptInfo_matches = ["*://*/*"];

let scriptInfo = {
  name: "grim-aibdp-checker",
  version: "1.0.0",
  description: "Check and display AIBDP status for websites",
  matches: scriptInfo_matches
};

let aibdpPath = "/.well-known/aibdp.json";

function parseStatus(str) {
  let match = str.toLowerCase();
  switch (match) {
    case "allowed" :
      return "Allowed";
    case "conditional" :
      return "Conditional";
    case "refused" :
      return "Refused";
    default:
      return "Unknown";
  }
}

function parsePolicy(json) {
  let obj = Belt_Option.getWithDefault(Js_json.decodeObject(json), {});
  let status = Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(obj, "status"), Js_json.decodeString), parseStatus), "Unknown");
  let conditions = Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(obj, "conditions"), Js_json.decodeArray), arr => Belt_Array.keepMap(arr, Js_json.decodeString)), []);
  return {
    status: status,
    conditions: conditions
  };
}

function parseManifest(json) {
  let obj = Js_json.decodeObject(json);
  if (obj === undefined) {
    return;
  }
  let version = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(obj, "aibdp_version"), Js_json.decodeString), "unknown");
  let contact = Belt_Option.flatMap(Js_dict.get(obj, "contact"), Js_json.decodeString);
  let expires = Belt_Option.flatMap(Js_dict.get(obj, "expires"), Js_json.decodeString);
  let policies = Belt_Option.getWithDefault(Belt_Option.flatMap(Js_dict.get(obj, "policies"), Js_json.decodeObject), {});
  let getPolicy = name => Belt_Option.getWithDefault(Belt_Option.map(Js_dict.get(policies, name), parsePolicy), {
    status: "Unknown",
    conditions: []
  });
  return {
    version: version,
    contact: contact,
    expires: expires,
    training: getPolicy("training"),
    indexing: getPolicy("indexing"),
    summarization: getPolicy("summarization"),
    generativeReuse: getPolicy("generative_reuse"),
    embedding: getPolicy("embedding")
  };
}

function fetchAibdp() {
  let url = Belt_Array.slice(location.href.split("/"), 0, 3).join("/") + aibdpPath;
  GrimCore.Log.debug(`Fetching AIBDP from: ` + url);
  let __x = GrimCore.HTTP.fetch(undefined, undefined, url);
  let __x$1 = Js_promise.then_(resp => {
    let httpStatus = resp.status;
    if (httpStatus !== 200) {
      if (httpStatus === 404) {
        return Promise.resolve("NotFound");
      } else {
        return Promise.resolve({
          TAG: "Error",
          _0: `HTTP ` + resp.status.toString()
        });
      }
    }
    try {
      let json = JSON.parse(resp.responseText);
      let manifest = parseManifest(json);
      if (manifest !== undefined) {
        return Promise.resolve({
          TAG: "Found",
          _0: manifest
        });
      } else {
        return Promise.resolve({
          TAG: "Error",
          _0: "Invalid AIBDP format"
        });
      }
    } catch (exn) {
      return Promise.resolve({
        TAG: "Error",
        _0: "Failed to parse AIBDP JSON"
      });
    }
  }, __x);
  return Js_promise.$$catch(param => Promise.resolve({
    TAG: "Error",
    _0: "Network error"
  }), __x$1);
}

function statusToEmoji(status) {
  switch (status) {
    case "Allowed" :
      return "✓";
    case "Refused" :
      return "🔒";
    case "Conditional" :
      return "⚠️";
    case "Unknown" :
      return "❓";
  }
}

function statusToVariant(status) {
  switch (status) {
    case "Allowed" :
      return "success";
    case "Refused" :
      return "error";
    case "Conditional" :
      return "warning";
    case "Unknown" :
      return "info";
  }
}

function statusToText(status) {
  switch (status) {
    case "Allowed" :
      return "Allowed";
    case "Refused" :
      return "Refused";
    case "Conditional" :
      return "Conditional";
    case "Unknown" :
      return "Unknown";
  }
}

let badgeCSS = `
  .grim-aibdp-badge {
    position: fixed;
    bottom: 20px;
    left: 20px;
    z-index: 99998;
    cursor: pointer;
    transition: transform 0.2s;
  }
  .grim-aibdp-badge:hover {
    transform: scale(1.1);
  }
  .grim-aibdp-detail {
    position: fixed;
    bottom: 60px;
    left: 20px;
    z-index: 99999;
    background: white;
    border: 1px solid #dfe6e9;
    border-radius: 8px;
    padding: 16px;
    min-width: 280px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    font-size: 13px;
    display: none;
  }
  .grim-aibdp-detail.visible {
    display: block;
  }
  .grim-aibdp-detail h4 {
    margin: 0 0 12px 0;
    font-size: 14px;
    color: #2d3436;
  }
  .grim-aibdp-policy-row {
    display: flex;
    justify-content: space-between;
    padding: 6px 0;
    border-bottom: 1px solid #f1f3f4;
  }
  .grim-aibdp-policy-row:last-child {
    border-bottom: none;
  }
  .grim-aibdp-policy-name {
    font-weight: 500;
    color: #636e72;
  }
  .grim-aibdp-policy-status {
    font-weight: 600;
  }
  .grim-aibdp-status-allowed { color: #27ae60; }
  .grim-aibdp-status-refused { color: #e74c3c; }
  .grim-aibdp-status-conditional { color: #f39c12; }
  .grim-aibdp-status-unknown { color: #95a5a6; }
  .grim-aibdp-meta {
    margin-top: 12px;
    padding-top: 12px;
    border-top: 1px solid #dfe6e9;
    font-size: 11px;
    color: #95a5a6;
  }
`;

function renderPolicyRow(name, policy) {
  let match = policy.status;
  let statusClass;
  switch (match) {
    case "Allowed" :
      statusClass = "allowed";
      break;
    case "Refused" :
      statusClass = "refused";
      break;
    case "Conditional" :
      statusClass = "conditional";
      break;
    case "Unknown" :
      statusClass = "unknown";
      break;
  }
  return `<div class="grim-aibdp-policy-row">
    <span class="grim-aibdp-policy-name">` + name + `</span>
    <span class="grim-aibdp-policy-status grim-aibdp-status-` + statusClass + `">
      ` + statusToEmoji(policy.status) + ` ` + statusToText(policy.status) + `
    </span>
  </div>`;
}

function createBadge(result) {
  GM_addStyle(badgeCSS);
  let match;
  if (typeof result !== "object") {
    match = [
      "❓ No AIBDP",
      "info"
    ];
  } else if (result.TAG === "Found") {
    let manifest = result._0;
    match = [
      statusToEmoji(manifest.training.status) + ` AIBDP`,
      statusToVariant(manifest.training.status)
    ];
  } else {
    match = [
      "⚠️ AIBDP Error",
      "warning"
    ];
  }
  let badgeContainer = GrimCore.DOM.create("div", "grim-aibdp-badge", undefined);
  let badge = GrimCore.UI.createBadge(match[0], match[1]);
  badgeContainer.appendChild(badge);
  let detailPanel = GrimCore.DOM.create("div", "grim-aibdp-detail", undefined);
  let detailContent;
  if (typeof result !== "object") {
    detailContent = `<h4>❓ No AIBDP Found</h4>
       <p>This site has not published an AI Boundary Declaration Protocol manifest.</p>
       <p style="font-size: 11px; color: #95a5a6;">
         Learn more at <a href="https://aibdp.org" target="_blank">aibdp.org</a>
       </p>`;
  } else if (result.TAG === "Found") {
    let manifest$1 = result._0;
    let policies = [
      [
        "AI Training",
        manifest$1.training
      ],
      [
        "Indexing",
        manifest$1.indexing
      ],
      [
        "Summarization",
        manifest$1.summarization
      ],
      [
        "Generative Reuse",
        manifest$1.generativeReuse
      ],
      [
        "Embedding",
        manifest$1.embedding
      ]
    ];
    let policyRows = Belt_Array.map(policies, param => renderPolicyRow(param[0], param[1])).join("");
    let contact = manifest$1.contact;
    let metaInfo = contact !== undefined ? `<div class="grim-aibdp-meta">Contact: ` + contact + `</div>` : "";
    detailContent = `<h4>🔐 AIBDP v` + manifest$1.version + `</h4>
       ` + policyRows + `
       ` + metaInfo;
  } else {
    detailContent = `<h4>⚠️ AIBDP Error</h4>
       <p>Could not fetch AIBDP manifest: ` + result._0 + `</p>`;
  }
  detailPanel.innerHTML = detailContent;
  badgeContainer.addEventListener("click", param => {
    detailPanel["classList.toggle"]("visible");
  });
  document.body.addEventListener("click", event => {
    (event.target);
    if (!(badgeContainer.contains(target)) && !(detailPanel.contains(target))) {
      detailPanel["classList.remove"]("visible");
      return;
    }
  });
  document.body.appendChild(badgeContainer);
  document.body.appendChild(detailPanel);
}

let cacheKey = "aibdp_cache";

function getCached() {
  let __x = GrimCore.Storage.getJson("Local", cacheKey);
  return Js_promise.then_(cached => {
    if (cached === undefined) {
      return Promise.resolve(undefined);
    }
    let obj = Belt_Option.getWithDefault(Js_json.decodeObject(cached), {});
    let host = Belt_Option.flatMap(Js_dict.get(obj, "host"), Js_json.decodeString);
    let timestamp = Belt_Option.flatMap(Js_dict.get(obj, "timestamp"), Js_json.decodeNumber);
    if (host === undefined) {
      return Promise.resolve(undefined);
    }
    if (timestamp === undefined) {
      return Promise.resolve(undefined);
    }
    if (!(host === location.host && Date.now() - timestamp < 3600000.0)) {
      return Promise.resolve(undefined);
    }
    let resultStr = Belt_Option.flatMap(Js_dict.get(obj, "result"), Js_json.decodeString);
    if (resultStr === undefined) {
      return Promise.resolve(undefined);
    }
    if (resultStr === "not_found") {
      return Promise.resolve("NotFound");
    }
    try {
      let parsed = JSON.parse(resultStr);
      let m = parseManifest(parsed);
      if (m !== undefined) {
        return Promise.resolve({
          TAG: "Found",
          _0: m
        });
      } else {
        return Promise.resolve(undefined);
      }
    } catch (exn) {
      return Promise.resolve(undefined);
    }
  }, __x);
}

function setCache(result) {
  let resultStr;
  resultStr = typeof result !== "object" ? "not_found" : (
      result.TAG === "Found" ? "found" : "error"
    );
  let cache = {};
  cache["host"] = location.host;
  cache["result"] = resultStr;
  cache["timestamp"] = Date.now();
  return GrimCore.Storage.setJson("Local", cacheKey, cache);
}

function run() {
  GrimCore.Log.info("AIBDP Checker running");
  let __x = getCached();
  Js_promise.then_(cached => {
    if (cached !== undefined) {
      GrimCore.Log.debug("Using cached AIBDP result");
      createBadge(cached);
      return Promise.resolve();
    }
    let __x = fetchAibdp();
    return Js_promise.then_(result => {
      createBadge(result);
      setCache(result);
      return Promise.resolve();
    }, __x);
  }, __x);
}

GrimCore.Registry.register("grim-aibdp-checker", scriptInfo);

document.body.addEventListener("load", param => run());

if ((document.readyState === "complete")) {
  run();
}

export {
  scriptInfo,
  aibdpPath,
  parseStatus,
  parsePolicy,
  parseManifest,
  fetchAibdp,
  statusToEmoji,
  statusToVariant,
  statusToText,
  badgeCSS,
  renderPolicyRow,
  createBadge,
  cacheKey,
  getCached,
  setCache,
  run,
}
/*  Not a pure module */
