// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GrimCore from "../../core/GrimCore.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Js_promise from "@rescript/runtime/lib/es6/Js_promise.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let scriptInfo_matches = [
  "*://gitlab.com/*",
  "*://*.gitlab.io/*"
];

let scriptInfo = {
  name: "grim-gitlab-enhanced",
  version: "1.0.0",
  description: "RSR-focused GitLab enhancements",
  matches: scriptInfo_matches
};

let tier1Languages = [
  [
    "Rust",
    "🦀"
  ],
  [
    "Elixir",
    "💧"
  ],
  [
    "Zig",
    "⚡"
  ],
  [
    "Ada",
    "🔧"
  ],
  [
    "SPARK",
    "🔧"
  ],
  [
    "Haskell",
    "λ"
  ],
  [
    "ReScript",
    "📜"
  ],
  [
    "OCaml",
    "🐫"
  ]
];

let tier2Languages = [
  [
    "Nickel",
    "🔩"
  ],
  [
    "Racket",
    "🎾"
  ],
  [
    "Scheme",
    "λ"
  ],
  [
    "Guile",
    "λ"
  ],
  [
    "Nix",
    "❄️"
  ],
  [
    "Dhall",
    "📋"
  ]
];

let prohibitedLanguages = [
  [
    "TypeScript",
    "🚫"
  ],
  [
    "JavaScript",
    "🚫"
  ],
  [
    "Python",
    "🐍"
  ],
  [
    "Go",
    "🚫"
  ],
  [
    "CUE",
    "🚫"
  ]
];

function getLanguageTier(lang) {
  let normalized = lang.toLowerCase();
  let findIn = (list, tier) => Belt_Option.map(Belt_Array.getBy(list, param => param[0].toLowerCase() === normalized), param => [
    tier,
    param[1]
  ]);
  return Belt_Option.getWithDefault(Belt_Option.orElse(Belt_Option.orElse(findIn(tier1Languages, "Tier1"), findIn(tier2Languages, "Tier2")), findIn(prohibitedLanguages, "Prohibited")), [
    "Unknown",
    "📦"
  ]);
}

let css = `
  .grim-rsr-badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 2px 8px;
    border-radius: 4px;
    font-size: 11px;
    font-weight: 600;
    margin-left: 8px;
  }
  .grim-rsr-tier1 { background: #d4edda; color: #155724; }
  .grim-rsr-tier2 { background: #fff3cd; color: #856404; }
  .grim-rsr-prohibited { background: #f8d7da; color: #721c24; }
  .grim-rsr-unknown { background: #e9ecef; color: #495057; }

  .grim-lang-badge {
    display: inline-flex;
    align-items: center;
    gap: 2px;
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 10px;
    margin: 2px;
  }

  .grim-state-viewer {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background: #1e1e1e;
    color: #d4d4d4;
    padding: 20px;
    border-radius: 8px;
    max-width: 600px;
    max-height: 80vh;
    overflow: auto;
    z-index: 100000;
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
    font-size: 13px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
  }
  .grim-state-viewer pre {
    margin: 0;
    white-space: pre-wrap;
  }
  .grim-state-viewer-close {
    position: absolute;
    top: 10px;
    right: 10px;
    cursor: pointer;
    font-size: 18px;
    opacity: 0.6;
  }
  .grim-state-viewer-close:hover { opacity: 1; }
  .grim-state-viewer-title {
    font-weight: 600;
    margin-bottom: 12px;
    color: #569cd6;
  }

  .grim-rsr-indicator {
    position: fixed;
    top: 60px;
    right: 20px;
    z-index: 99990;
    background: white;
    border: 1px solid #dfe6e9;
    border-radius: 8px;
    padding: 12px 16px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    font-size: 12px;
  }
  .grim-rsr-indicator-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 4px 0;
  }
  .grim-rsr-indicator-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
  }
  .grim-rsr-indicator-dot.green { background: #27ae60; }
  .grim-rsr-indicator-dot.yellow { background: #f39c12; }
  .grim-rsr-indicator-dot.red { background: #e74c3c; }
  .grim-rsr-indicator-dot.gray { background: #95a5a6; }
`;

function isRepoPage() {
  let path = location.pathname;
  let parts = Belt_Array.keep(path.split("/"), s => s !== "");
  if (parts.length >= 2 && !path.includes("/explore")) {
    return !path.includes("/dashboard");
  } else {
    return false;
  }
}

function getRepoPath() {
  if (!isRepoPage()) {
    return;
  }
  let path = location.pathname;
  let parts = Belt_Array.keep(path.split("/"), s => s !== "");
  return Belt_Array.slice(parts, 0, 3).join("/");
}

function checkFile(repoPath, filePath) {
  let url = `https://gitlab.com/` + repoPath + `/-/raw/main/` + filePath;
  let __x = GrimCore.HTTP.fetch(undefined, undefined, url);
  let __x$1 = Js_promise.then_(resp => Promise.resolve(resp.status === 200), __x);
  return Js_promise.$$catch(param => Promise.resolve(false), __x$1);
}

function fetchStateScm(repoPath) {
  let url = `https://gitlab.com/` + repoPath + `/-/raw/main/STATE.scm`;
  let __x = GrimCore.HTTP.fetch(undefined, undefined, url);
  let __x$1 = Js_promise.then_(resp => {
    if (resp.status === 200) {
      return Promise.resolve(resp.responseText);
    } else {
      return Promise.resolve(undefined);
    }
  }, __x);
  return Js_promise.$$catch(param => Promise.resolve(undefined), __x$1);
}

function getRepoLanguages() {
  let langElements = GrimCore.DOM.queryAll(".repository-language-bar-tooltip, [data-testid='language-stats'] span");
  return Belt_Array.keep(Belt_Array.map(langElements, el => el.textContent.trim()), s => {
    if (s !== "") {
      return !s.includes("%");
    } else {
      return false;
    }
  });
}

function createRsrBadge(tier, text) {
  let className;
  switch (tier) {
    case "Tier1" :
      className = "grim-rsr-badge grim-rsr-tier1";
      break;
    case "Tier2" :
      className = "grim-rsr-badge grim-rsr-tier2";
      break;
    case "Prohibited" :
      className = "grim-rsr-badge grim-rsr-prohibited";
      break;
    case "Unknown" :
      className = "grim-rsr-badge grim-rsr-unknown";
      break;
  }
  let badge = GrimCore.DOM.create("span", className, undefined);
  badge.textContent = text;
  return badge;
}

function createLanguageBadge(lang) {
  let match = getLanguageTier(lang);
  let className;
  switch (match[0]) {
    case "Tier1" :
      className = "grim-lang-badge grim-rsr-tier1";
      break;
    case "Tier2" :
      className = "grim-lang-badge grim-rsr-tier2";
      break;
    case "Prohibited" :
      className = "grim-lang-badge grim-rsr-prohibited";
      break;
    case "Unknown" :
      className = "grim-lang-badge grim-rsr-unknown";
      break;
  }
  let badge = GrimCore.DOM.create("span", className, undefined);
  badge.textContent = match[1] + ` ` + lang;
  return badge;
}

function showStateViewer(content) {
  let el = GrimCore.DOM.query(".grim-state-viewer");
  if (el !== undefined) {
    Primitive_option.valFromOption(el).remove();
  }
  let viewer = GrimCore.DOM.create("div", "grim-state-viewer", undefined);
  viewer.innerHTML = `
    <span class="grim-state-viewer-close">✕</span>
    <div class="grim-state-viewer-title">📋 STATE.scm</div>
    <pre>` + content + `</pre>
  `;
  document.body.appendChild(viewer);
  let closeBtn = GrimCore.DOM.query(".grim-state-viewer-close");
  if (closeBtn !== undefined) {
    Primitive_option.valFromOption(closeBtn).addEventListener("click", param => {
      viewer.remove();
    });
  }
  document.body.addEventListener("keydown", event => {
    if ((event.key === "Escape")) {
      viewer.remove();
      return;
    }
  });
}

function createRsrIndicator(info) {
  let indicator = GrimCore.DOM.create("div", "grim-rsr-indicator", undefined);
  let rows = [
    [
      info.hasStateScm,
      "STATE.scm"
    ],
    [
      info.hasAibdp,
      "AIBDP"
    ]
  ];
  let rowsHtml = Belt_Array.map(rows, param => {
    let present = param[0];
    let dotClass = present ? "green" : "gray";
    let status = present ? "✓" : "✗";
    return `<div class="grim-rsr-indicator-row">
      <span class="grim-rsr-indicator-dot ` + dotClass + `"></span>
      <span>` + status + ` ` + param[1] + `</span>
    </div>`;
  }).join("");
  let hasTier1 = Belt_Array.some(info.languages, l => l.tier === "Tier1");
  let hasProhibited = Belt_Array.some(info.languages, l => l.tier === "Prohibited");
  let complianceClass = hasProhibited ? "red" : (
      hasTier1 ? "green" : "yellow"
    );
  let complianceText = hasProhibited ? "⚠️ Has prohibited languages" : (
      hasTier1 ? "✓ RSR Tier 1" : "○ Unknown tier"
    );
  indicator.innerHTML = `
    <strong>RSR Status</strong>
    ` + rowsHtml + `
    <div class="grim-rsr-indicator-row">
      <span class="grim-rsr-indicator-dot ` + complianceClass + `"></span>
      <span>` + complianceText + `</span>
    </div>
  `;
  document.body.appendChild(indicator);
}

function enhanceRepoPage(repoPath) {
  GrimCore.Log.info(`Enhancing repo: ` + repoPath);
  let __x = Promise.all([
    checkFile(repoPath, "STATE.scm"),
    checkFile(repoPath, ".well-known/aibdp.json")
  ]);
  Js_promise.then_(param => {
    let hasAibdp = param[1];
    let hasState = param[0];
    let languages = Belt_Array.map(getRepoLanguages(), name => {
      let match = getLanguageTier(name);
      return {
        name: name,
        tier: match[0],
        emoji: match[1]
      };
    });
    let info_rsrCompliant = hasState && hasAibdp;
    let info = {
      hasStateScm: hasState,
      hasAibdp: hasAibdp,
      languages: languages,
      rsrCompliant: info_rsrCompliant
    };
    createRsrIndicator(info);
    if (hasState) {
      GM_registerMenuCommand("View STATE.scm", () => {
        let __x = fetchStateScm(repoPath);
        Js_promise.then_(content => {
          if (content !== undefined) {
            showStateViewer(content);
          } else {
            GrimCore.UI.toast("Failed to load STATE.scm", undefined);
          }
          return Promise.resolve();
        }, __x);
      });
    }
    return Promise.resolve();
  }, __x);
  let langBar = GrimCore.DOM.query(".repository-languages, [data-testid='language-stats']");
  if (langBar === undefined) {
    return;
  }
  let el = Primitive_option.valFromOption(langBar);
  let langNames = getRepoLanguages();
  Belt_Array.forEach(langNames, name => {
    let badge = createLanguageBadge(name);
    el.appendChild(badge);
  });
}

function enhanceProjectList() {
  let projectCards = GrimCore.DOM.queryAll(".project-card, .project-row");
  Belt_Array.forEach(projectCards, card => {
    let link = (card.querySelector('a.project'));
    if (!(link == null)) {
      ((link.getAttribute('href')));
      return;
    }
  });
}

function run() {
  if (!GrimCore.URL.isGitLab()) {
    return;
  }
  GrimCore.Log.info("GitLab Enhanced running");
  GM_addStyle(css);
  let repoPath = getRepoPath();
  if (repoPath !== undefined) {
    enhanceRepoPage(repoPath);
  } else {
    enhanceProjectList();
  }
  GM_registerMenuCommand("Show RSR Info", () => {
    let path = getRepoPath();
    if (path !== undefined) {
      return GrimCore.UI.toast(`Repo: ` + path, undefined);
    } else {
      return GrimCore.UI.toast("Not on a repo page", undefined);
    }
  });
}

GrimCore.Registry.register("grim-gitlab-enhanced", scriptInfo);

if ((document.readyState === "complete")) {
  run();
} else {
  document.body.addEventListener("DOMContentLoaded", param => run());
}

export {
  scriptInfo,
  tier1Languages,
  tier2Languages,
  prohibitedLanguages,
  getLanguageTier,
  css,
  isRepoPage,
  getRepoPath,
  checkFile,
  fetchStateScm,
  getRepoLanguages,
  createRsrBadge,
  createLanguageBadge,
  showStateViewer,
  createRsrIndicator,
  enhanceRepoPage,
  enhanceProjectList,
  run,
}
/*  Not a pure module */
