// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_promise from "@rescript/runtime/lib/es6/Js_promise.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let GM = {};

let $$default = {
  version: "1.0.0",
  debug: false,
  prefix: "grim"
};

let current = {
  contents: $$default
};

function setDebug(enabled) {
  let init = current.contents;
  current.contents = {
    version: init.version,
    debug: enabled,
    prefix: init.prefix
  };
}

function isDebug() {
  return current.contents.debug;
}

let Config = {
  $$default: $$default,
  current: current,
  setDebug: setDebug,
  isDebug: isDebug
};

let prefix = "[Grim]";

function info(msg) {
  console.log(prefix, msg);
}

function warn(msg) {
  console.warn(prefix, msg);
}

function error(msg) {
  console.error(prefix, msg);
}

function debug(msg) {
  if (current.contents.debug) {
    console.log(prefix, "[DEBUG]", msg);
    return;
  }
}

let Log = {
  prefix: prefix,
  info: info,
  warn: warn,
  error: error,
  debug: debug
};

function query(selector) {
  return Primitive_option.fromNullable(document.querySelector(selector));
}

function queryAll(selector) {
  document.querySelectorAll(selector);
  return (Array.from(nodeList));
}

function create(tag, classNameOpt, idOpt) {
  let className = classNameOpt !== undefined ? classNameOpt : "";
  let id = idOpt !== undefined ? idOpt : "";
  let el = document.createElement(tag);
  if (className !== "") {
    el["classList.add"](className);
  }
  if (id !== "") {
    el.setAttribute("id", id);
  }
  return el;
}

function waitFor(selector, timeoutOpt) {
  let timeout = timeoutOpt !== undefined ? timeoutOpt : 5000;
  return new Promise((resolve, param) => {
    let startTime = Date.now();
    let check = () => {
      let el = Primitive_option.fromNullable(document.querySelector(selector));
      if (el !== undefined) {
        return resolve(Primitive_option.some(Primitive_option.valFromOption(el)));
      } else if (Date.now() - startTime > timeout) {
        return resolve(undefined);
      } else {
        setTimeout(check, 100);
        return;
      }
    };
    check();
  });
}

let DOM = {
  query: query,
  queryAll: queryAll,
  create: create,
  waitFor: waitFor
};

let storagePrefix = "grim_";

function prefixKey(key) {
  return storagePrefix + key;
}

function get(storageOpt, key) {
  let storage = storageOpt !== undefined ? storageOpt : "Local";
  let prefixedKey = storagePrefix + key;
  switch (storage) {
    case "Local" :
      return Promise.resolve(Primitive_option.fromNullable(localStorage.getItem(prefixedKey)));
    case "Session" :
      return Promise.resolve(Primitive_option.fromNullable(sessionStorage.getItem(prefixedKey)));
    case "GM" :
      let __x = GM_getValue(prefixedKey, "");
      return Js_promise.then_(value => Promise.resolve(value === "" ? undefined : value), __x);
  }
}

function set(storageOpt, key, value) {
  let storage = storageOpt !== undefined ? storageOpt : "Local";
  let prefixedKey = storagePrefix + key;
  switch (storage) {
    case "Local" :
      localStorage.setItem(prefixedKey, value);
      return Promise.resolve();
    case "Session" :
      sessionStorage.setItem(prefixedKey, value);
      return Promise.resolve();
    case "GM" :
      return GM_setValue(prefixedKey, value);
  }
}

function remove(storageOpt, key) {
  let storage = storageOpt !== undefined ? storageOpt : "Local";
  let prefixedKey = storagePrefix + key;
  switch (storage) {
    case "Local" :
      localStorage.removeItem(prefixedKey);
      return Promise.resolve();
    case "Session" :
      sessionStorage.removeItem(prefixedKey);
      return Promise.resolve();
    case "GM" :
      return GM_deleteValue(prefixedKey);
  }
}

function getJson(storageOpt, key) {
  let storage = storageOpt !== undefined ? storageOpt : "Local";
  let __x = get(storage, key);
  return Js_promise.then_(value => {
    if (value === undefined) {
      return Promise.resolve(undefined);
    }
    try {
      return Promise.resolve(JSON.parse(value));
    } catch (exn) {
      return Promise.resolve(undefined);
    }
  }, __x);
}

function setJson(storageOpt, key, value) {
  let storage = storageOpt !== undefined ? storageOpt : "Local";
  return set(storage, key, JSON.stringify(value));
}

let Storage = {
  storagePrefix: storagePrefix,
  prefixKey: prefixKey,
  get: get,
  set: set,
  remove: remove,
  getJson: getJson,
  setJson: setJson
};

function methodToString(m) {
  switch (m) {
    case "GET" :
      return "GET";
    case "POST" :
      return "POST";
    case "PUT" :
      return "PUT";
    case "DELETE" :
      return "DELETE";
    case "PATCH" :
      return "PATCH";
  }
}

function fetch(methodOpt, headers, url) {
  let method = methodOpt !== undefined ? methodOpt : "GET";
  return new Promise((resolve, reject) => {
    GM_xmlHttpRequest({
      method: methodToString(method),
      url: url,
      headers: headers,
      onload: resp => resolve({
        status: resp.status,
        statusText: resp.statusText,
        responseText: resp.responseText,
        responseHeaders: resp.responseHeaders
      }),
      onerror: err => reject(Stdlib_Exn.raiseError((err.statusText || "Network error")))
    });
  });
}

function fetchJson(methodOpt, headers, url) {
  let method = methodOpt !== undefined ? methodOpt : "GET";
  let __x = fetch(method, headers, url);
  return Js_promise.then_(resp => Promise.resolve(JSON.parse(resp.responseText)), __x);
}

let HTTP = {
  methodToString: methodToString,
  fetch: fetch,
  fetchJson: fetchJson
};

let baseCSS = `
    .grim-panel {
      position: fixed;
      z-index: 99999;
      background: #ffffff;
      border: 1px solid #dfe6e9;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 14px;
      color: #2d3436;
    }
    .grim-panel-header {
      padding: 12px 16px;
      border-bottom: 1px solid #dfe6e9;
      font-weight: 600;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .grim-panel-body {
      padding: 16px;
      max-height: 400px;
      overflow-y: auto;
    }
    .grim-panel-close {
      cursor: pointer;
      opacity: 0.6;
      transition: opacity 0.2s;
    }
    .grim-panel-close:hover {
      opacity: 1;
    }
    .grim-badge {
      display: inline-flex;
      align-items: center;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 500;
    }
    .grim-badge-success { background: #d4edda; color: #155724; }
    .grim-badge-warning { background: #fff3cd; color: #856404; }
    .grim-badge-error { background: #f8d7da; color: #721c24; }
    .grim-badge-info { background: #cce5ff; color: #004085; }
    .grim-toast {
      position: fixed;
      bottom: 20px;
      right: 20px;
      padding: 12px 24px;
      background: #2d3436;
      color: #ffffff;
      border-radius: 8px;
      z-index: 100000;
      animation: grim-toast-in 0.3s ease;
    }
    @keyframes grim-toast-in {
      from { transform: translateY(100%); opacity: 0; }
      to { transform: translateY(0); opacity: 1; }
    }
    .grim-toast-out {
      animation: grim-toast-out 0.3s ease forwards;
    }
    @keyframes grim-toast-out {
      from { transform: translateY(0); opacity: 1; }
      to { transform: translateY(100%); opacity: 0; }
    }
  `;

let initialized = {
  contents: false
};

function init() {
  if (!initialized.contents) {
    GM_addStyle(baseCSS);
    initialized.contents = true;
    return debug("UI initialized");
  }
}

function createPanel(title, positionOpt, draggableOpt) {
  let position = positionOpt !== undefined ? positionOpt : [
      20,
      20
    ];
  init();
  let panel = create("div", "grim-panel", undefined);
  panel["style.cssText"] = `top: ` + position[0].toString() + `px; right: ` + position[1].toString() + `px;`;
  panel.innerHTML = `
      <div class="grim-panel-header">
        <span>` + title + `</span>
        <span class="grim-panel-close">✕</span>
      </div>
      <div class="grim-panel-body"></div>
    `;
  let btn = Primitive_option.fromNullable(document.querySelector(".grim-panel-close"));
  if (btn !== undefined) {
    Primitive_option.valFromOption(btn).addEventListener("click", param => {
      panel.remove();
    });
  }
  document.body.appendChild(panel);
  return panel;
}

function toast(message, durationOpt) {
  let duration = durationOpt !== undefined ? durationOpt : 3000;
  init();
  let toastEl = create("div", "grim-toast", undefined);
  toastEl.textContent = message;
  document.body.appendChild(toastEl);
  setTimeout(() => {
    toastEl["classList.add"]("grim-toast-out");
    setTimeout(() => {
      toastEl.remove();
    }, 300);
  }, duration);
}

function createBadge(text, variantOpt) {
  let variant = variantOpt !== undefined ? variantOpt : "info";
  let badge = create("span", `grim-badge grim-badge-` + variant, undefined);
  badge.textContent = text;
  return badge;
}

let UI = {
  baseCSS: baseCSS,
  initialized: initialized,
  init: init,
  createPanel: createPanel,
  toast: toast,
  createBadge: createBadge
};

let scripts = {};

function register(name, info) {
  scripts[name] = info;
  debug(`Registered script: ` + name);
}

function get$1(name) {
  return Js_dict.get(scripts, name);
}

function list() {
  return Object.keys(scripts);
}

let Registry = {
  scripts: scripts,
  register: register,
  get: get$1,
  list: list
};

function isGitLab() {
  return location.host.includes("gitlab");
}

function isGitHub() {
  return location.host.includes("github");
}

function isCodeberg() {
  return location.host.includes("codeberg");
}

function matchesPattern(pattern) {
  let regex = pattern.replace(/\*/g, ".*").replace(/\?/g, ".");
  return new RegExp(regex).test(location.href);
}

let URL = {
  isGitLab: isGitLab,
  isGitHub: isGitHub,
  isCodeberg: isCodeberg,
  matchesPattern: matchesPattern
};

function init$1(debugOpt) {
  let debug = debugOpt !== undefined ? debugOpt : false;
  setDebug(debug);
  console.log(prefix, "GrimCore initialized v1.0.0");
}

export {
  GM,
  Config,
  Log,
  DOM,
  Storage,
  HTTP,
  UI,
  Registry,
  URL,
  init$1 as init,
}
/* No side effect */
